/*
 *  Copyright (c) 2010 David Koch
 *
 *  See the file "license.terms" for information on usage and redistribution
 *  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 *     $Id: exdl_gl3_fp.h,v 1.5 2005/06/29 14:45:38 dgud Exp $
 */

/* File included in "exdl_wrapper.c" */

#ifdef COMPILE_GL3

/* GL_VERSION_1_0 */
{ glCullFace_ENUM,                                     "glCullFace",                                     egl3_cullFace },
{ glFrontFace_ENUM,                                    "glFrontFace",                                    egl3_frontFace },
{ glHint_ENUM,                                         "glHint",                                         egl3_hint },
{ glLineWidth_ENUM,                                    "glLineWidth",                                    egl3_lineWidth },
{ glPointSize_ENUM,                                    "glPointSize",                                    egl3_pointSize },
{ glPolygonMode_ENUM,                                  "glPolygonMode",                                  egl3_polygonMode },
{ glScissor_ENUM,                                      "glScissor",                                      egl3_scissor },
{ glTexParameterf_ENUM,                                "glTexParameterf",                                egl3_texParameterf },
{ glTexParameterfv_ENUM,                               "glTexParameterfv",                               egl3_texParameterfv },
{ glTexParameteri_ENUM,                                "glTexParameteri",                                egl3_texParameteri },
{ glTexParameteriv_ENUM,                               "glTexParameteriv",                               egl3_texParameteriv },
{ glTexImage1D_ENUM,                                   "glTexImage1D",                                   egl3_texImage1D },
{ glTexImage2D_ENUM,                                   "glTexImage2D",                                   egl3_texImage2D },
{ glDrawBuffer_ENUM,                                   "glDrawBuffer",                                   egl3_drawBuffer },
{ glClear_ENUM,                                        "glClear",                                        egl3_clear },
{ glClearColor_ENUM,                                   "glClearColor",                                   egl3_clearColor },
{ glClearStencil_ENUM,                                 "glClearStencil",                                 egl3_clearStencil },
{ glClearDepth_ENUM,                                   "glClearDepth",                                   egl3_clearDepth },
{ glStencilMask_ENUM,                                  "glStencilMask",                                  egl3_stencilMask },
{ glColorMask_ENUM,                                    "glColorMask",                                    egl3_colorMask },
{ glDepthMask_ENUM,                                    "glDepthMask",                                    egl3_depthMask },
{ glDisable_ENUM,                                      "glDisable",                                      egl3_disable },
{ glEnable_ENUM,                                       "glEnable",                                       egl3_enable },
{ glFinish_ENUM,                                       "glFinish",                                       egl3_finish },
{ glFlush_ENUM,                                        "glFlush",                                        egl3_flush },
{ glBlendFunc_ENUM,                                    "glBlendFunc",                                    egl3_blendFunc },
{ glLogicOp_ENUM,                                      "glLogicOp",                                      egl3_logicOp },
{ glStencilFunc_ENUM,                                  "glStencilFunc",                                  egl3_stencilFunc },
{ glStencilOp_ENUM,                                    "glStencilOp",                                    egl3_stencilOp },
{ glDepthFunc_ENUM,                                    "glDepthFunc",                                    egl3_depthFunc },
{ glPixelStoref_ENUM,                                  "glPixelStoref",                                  egl3_pixelStoref },
{ glPixelStorei_ENUM,                                  "glPixelStorei",                                  egl3_pixelStorei },
{ glReadBuffer_ENUM,                                   "glReadBuffer",                                   egl3_readBuffer },
{ glReadPixels_ENUM,                                   "glReadPixels",                                   egl3_readPixels },
{ glGetBooleanv_ENUM,                                  "glGetBooleanv",                                  egl3_getBooleanv },
{ glGetDoublev_ENUM,                                   "glGetDoublev",                                   egl3_getDoublev },
{ glGetError_ENUM,                                     "glGetError",                                     egl3_getError },
{ glGetFloatv_ENUM,                                    "glGetFloatv",                                    egl3_getFloatv },
{ glGetIntegerv_ENUM,                                  "glGetIntegerv",                                  egl3_getIntegerv },
{ glGetString_ENUM,                                    "glGetString",                                    egl3_getString },
{ glGetTexImage_ENUM,                                  "glGetTexImage",                                  egl3_getTexImage },
{ glGetTexParameterfv_ENUM,                            "glGetTexParameterfv",                            egl3_getTexParameterfv },
{ glGetTexParameteriv_ENUM,                            "glGetTexParameteriv",                            egl3_getTexParameteriv },
{ glGetTexLevelParameterfv_ENUM,                       "glGetTexLevelParameterfv",                       egl3_getTexLevelParameterfv },
{ glGetTexLevelParameteriv_ENUM,                       "glGetTexLevelParameteriv",                       egl3_getTexLevelParameteriv },
{ glIsEnabled_ENUM,                                    "glIsEnabled",                                    egl3_isEnabled },
{ glDepthRange_ENUM,                                   "glDepthRange",                                   egl3_depthRange },
{ glViewport_ENUM,                                     "glViewport",                                     egl3_viewport },
/* GL_VERSION_1_1 */
{ glDrawArrays_ENUM,                                   "glDrawArrays",                                   egl3_drawArrays },
{ glDrawElements_ENUM,                                 "glDrawElements",                                 egl3_drawElements },
{ glGetPointerv_ENUM,                                  "glGetPointerv",                                  egl3_getPointerv },
{ glPolygonOffset_ENUM,                                "glPolygonOffset",                                egl3_polygonOffset },
{ glCopyTexImage1D_ENUM,                               "glCopyTexImage1D",                               egl3_copyTexImage1D },
{ glCopyTexImage2D_ENUM,                               "glCopyTexImage2D",                               egl3_copyTexImage2D },
{ glCopyTexSubImage1D_ENUM,                            "glCopyTexSubImage1D",                            egl3_copyTexSubImage1D },
{ glCopyTexSubImage2D_ENUM,                            "glCopyTexSubImage2D",                            egl3_copyTexSubImage2D },
{ glTexSubImage1D_ENUM,                                "glTexSubImage1D",                                egl3_texSubImage1D },
{ glTexSubImage2D_ENUM,                                "glTexSubImage2D",                                egl3_texSubImage2D },
{ glBindTexture_ENUM,                                  "glBindTexture",                                  egl3_bindTexture },
{ glDeleteTextures_ENUM,                               "glDeleteTextures",                               egl3_deleteTextures },
{ glGenTextures_ENUM,                                  "glGenTextures",                                  egl3_genTextures },
{ glIsTexture_ENUM,                                    "glIsTexture",                                    egl3_isTexture },
/* GL_VERSION_1_2 */
{ glBlendColor_ENUM,                                   "glBlendColor",                                   egl3_blendColor },
{ glBlendEquation_ENUM,                                "glBlendEquation",                                egl3_blendEquation },
{ glDrawRangeElements_ENUM,                            "glDrawRangeElements",                            egl3_drawRangeElements },
{ glTexImage3D_ENUM,                                   "glTexImage3D",                                   egl3_texImage3D },
{ glTexSubImage3D_ENUM,                                "glTexSubImage3D",                                egl3_texSubImage3D },
{ glCopyTexSubImage3D_ENUM,                            "glCopyTexSubImage3D",                            egl3_copyTexSubImage3D },
/* GL_VERSION_1_3 */
{ glActiveTexture_ENUM,                                "glActiveTexture",                                egl3_activeTexture },
{ glSampleCoverage_ENUM,                               "glSampleCoverage",                               egl3_sampleCoverage },
{ glCompressedTexImage3D_ENUM,                         "glCompressedTexImage3D",                         egl3_compressedTexImage3D },
{ glCompressedTexImage2D_ENUM,                         "glCompressedTexImage2D",                         egl3_compressedTexImage2D },
{ glCompressedTexImage1D_ENUM,                         "glCompressedTexImage1D",                         egl3_compressedTexImage1D },
{ glCompressedTexSubImage3D_ENUM,                      "glCompressedTexSubImage3D",                      egl3_compressedTexSubImage3D },
{ glCompressedTexSubImage2D_ENUM,                      "glCompressedTexSubImage2D",                      egl3_compressedTexSubImage2D },
{ glCompressedTexSubImage1D_ENUM,                      "glCompressedTexSubImage1D",                      egl3_compressedTexSubImage1D },
{ glGetCompressedTexImage_ENUM,                        "glGetCompressedTexImage",                        egl3_getCompressedTexImage },
/* GL_VERSION_1_4 */
{ glBlendFuncSeparate_ENUM,                            "glBlendFuncSeparate",                            egl3_blendFuncSeparate },
{ glMultiDrawArrays_ENUM,                              "glMultiDrawArrays",                              egl3_multiDrawArrays },
{ glMultiDrawElements_ENUM,                            "glMultiDrawElements",                            egl3_multiDrawElements },
{ glPointParameterf_ENUM,                              "glPointParameterf",                              egl3_pointParameterf },
{ glPointParameterfv_ENUM,                             "glPointParameterfv",                             egl3_pointParameterfv },
{ glPointParameteri_ENUM,                              "glPointParameteri",                              egl3_pointParameteri },
{ glPointParameteriv_ENUM,                             "glPointParameteriv",                             egl3_pointParameteriv },
/* GL_VERSION_1_5 */
{ glGenQueries_ENUM,                                   "glGenQueries",                                   egl3_genQueries },
{ glDeleteQueries_ENUM,                                "glDeleteQueries",                                egl3_deleteQueries },
{ glIsQuery_ENUM,                                      "glIsQuery",                                      egl3_isQuery },
{ glBeginQuery_ENUM,                                   "glBeginQuery",                                   egl3_beginQuery },
{ glEndQuery_ENUM,                                     "glEndQuery",                                     egl3_endQuery },
{ glGetQueryiv_ENUM,                                   "glGetQueryiv",                                   egl3_getQueryiv },
{ glGetQueryObjectiv_ENUM,                             "glGetQueryObjectiv",                             egl3_getQueryObjectiv },
{ glGetQueryObjectuiv_ENUM,                            "glGetQueryObjectuiv",                            egl3_getQueryObjectuiv },
{ glBindBuffer_ENUM,                                   "glBindBuffer",                                   egl3_bindBuffer },
{ glDeleteBuffers_ENUM,                                "glDeleteBuffers",                                egl3_deleteBuffers },
{ glGenBuffers_ENUM,                                   "glGenBuffers",                                   egl3_genBuffers },
{ glIsBuffer_ENUM,                                     "glIsBuffer",                                     egl3_isBuffer },
{ glBufferData_ENUM,                                   "glBufferData",                                   egl3_bufferData },
{ glBufferSubData_ENUM,                                "glBufferSubData",                                egl3_bufferSubData },
{ glGetBufferSubData_ENUM,                             "glGetBufferSubData",                             egl3_getBufferSubData },
{ glMapBuffer_ENUM,                                    "glMapBuffer",                                    egl3_mapBuffer },
{ glUnmapBuffer_ENUM,                                  "glUnmapBuffer",                                  egl3_unmapBuffer },
{ glGetBufferParameteriv_ENUM,                         "glGetBufferParameteriv",                         egl3_getBufferParameteriv },
{ glGetBufferPointerv_ENUM,                            "glGetBufferPointerv",                            egl3_getBufferPointerv },
/* GL_VERSION_2_0 */
{ glBlendEquationSeparate_ENUM,                        "glBlendEquationSeparate",                        egl3_blendEquationSeparate },
{ glDrawBuffers_ENUM,                                  "glDrawBuffers",                                  egl3_drawBuffers },
{ glStencilOpSeparate_ENUM,                            "glStencilOpSeparate",                            egl3_stencilOpSeparate },
{ glStencilFuncSeparate_ENUM,                          "glStencilFuncSeparate",                          egl3_stencilFuncSeparate },
{ glStencilMaskSeparate_ENUM,                          "glStencilMaskSeparate",                          egl3_stencilMaskSeparate },
{ glAttachShader_ENUM,                                 "glAttachShader",                                 egl3_attachShader },
{ glBindAttribLocation_ENUM,                           "glBindAttribLocation",                           egl3_bindAttribLocation },
{ glCompileShader_ENUM,                                "glCompileShader",                                egl3_compileShader },
{ glCreateProgram_ENUM,                                "glCreateProgram",                                egl3_createProgram },
{ glCreateShader_ENUM,                                 "glCreateShader",                                 egl3_createShader },
{ glDeleteProgram_ENUM,                                "glDeleteProgram",                                egl3_deleteProgram },
{ glDeleteShader_ENUM,                                 "glDeleteShader",                                 egl3_deleteShader },
{ glDetachShader_ENUM,                                 "glDetachShader",                                 egl3_detachShader },
{ glDisableVertexAttribArray_ENUM,                     "glDisableVertexAttribArray",                     egl3_disableVertexAttribArray },
{ glEnableVertexAttribArray_ENUM,                      "glEnableVertexAttribArray",                      egl3_enableVertexAttribArray },
{ glGetActiveAttrib_ENUM,                              "glGetActiveAttrib",                              egl3_getActiveAttrib },
{ glGetActiveUniform_ENUM,                             "glGetActiveUniform",                             egl3_getActiveUniform },
{ glGetAttachedShaders_ENUM,                           "glGetAttachedShaders",                           egl3_getAttachedShaders },
{ glGetAttribLocation_ENUM,                            "glGetAttribLocation",                            egl3_getAttribLocation },
{ glGetProgramiv_ENUM,                                 "glGetProgramiv",                                 egl3_getProgramiv },
{ glGetProgramInfoLog_ENUM,                            "glGetProgramInfoLog",                            egl3_getProgramInfoLog },
{ glGetShaderiv_ENUM,                                  "glGetShaderiv",                                  egl3_getShaderiv },
{ glGetShaderInfoLog_ENUM,                             "glGetShaderInfoLog",                             egl3_getShaderInfoLog },
{ glGetShaderSource_ENUM,                              "glGetShaderSource",                              egl3_getShaderSource },
{ glGetUniformLocation_ENUM,                           "glGetUniformLocation",                           egl3_getUniformLocation },
{ glGetUniformfv_ENUM,                                 "glGetUniformfv",                                 egl3_getUniformfv },
{ glGetUniformiv_ENUM,                                 "glGetUniformiv",                                 egl3_getUniformiv },
{ glGetVertexAttribdv_ENUM,                            "glGetVertexAttribdv",                            egl3_getVertexAttribdv },
{ glGetVertexAttribfv_ENUM,                            "glGetVertexAttribfv",                            egl3_getVertexAttribfv },
{ glGetVertexAttribiv_ENUM,                            "glGetVertexAttribiv",                            egl3_getVertexAttribiv },
{ glGetVertexAttribPointerv_ENUM,                      "glGetVertexAttribPointerv",                      egl3_getVertexAttribPointerv },
{ glIsProgram_ENUM,                                    "glIsProgram",                                    egl3_isProgram },
{ glIsShader_ENUM,                                     "glIsShader",                                     egl3_isShader },
{ glLinkProgram_ENUM,                                  "glLinkProgram",                                  egl3_linkProgram },
{ glShaderSource_ENUM,                                 "glShaderSource",                                 egl3_shaderSource },
{ glUseProgram_ENUM,                                   "glUseProgram",                                   egl3_useProgram },
{ glUniform1f_ENUM,                                    "glUniform1f",                                    egl3_uniform1f },
{ glUniform2f_ENUM,                                    "glUniform2f",                                    egl3_uniform2f },
{ glUniform3f_ENUM,                                    "glUniform3f",                                    egl3_uniform3f },
{ glUniform4f_ENUM,                                    "glUniform4f",                                    egl3_uniform4f },
{ glUniform1i_ENUM,                                    "glUniform1i",                                    egl3_uniform1i },
{ glUniform2i_ENUM,                                    "glUniform2i",                                    egl3_uniform2i },
{ glUniform3i_ENUM,                                    "glUniform3i",                                    egl3_uniform3i },
{ glUniform4i_ENUM,                                    "glUniform4i",                                    egl3_uniform4i },
{ glUniform1fv_ENUM,                                   "glUniform1fv",                                   egl3_uniform1fv },
{ glUniform2fv_ENUM,                                   "glUniform2fv",                                   egl3_uniform2fv },
{ glUniform3fv_ENUM,                                   "glUniform3fv",                                   egl3_uniform3fv },
{ glUniform4fv_ENUM,                                   "glUniform4fv",                                   egl3_uniform4fv },
{ glUniform1iv_ENUM,                                   "glUniform1iv",                                   egl3_uniform1iv },
{ glUniform2iv_ENUM,                                   "glUniform2iv",                                   egl3_uniform2iv },
{ glUniform3iv_ENUM,                                   "glUniform3iv",                                   egl3_uniform3iv },
{ glUniform4iv_ENUM,                                   "glUniform4iv",                                   egl3_uniform4iv },
{ glUniformMatrix2fv_ENUM,                             "glUniformMatrix2fv",                             egl3_uniformMatrix2fv },
{ glUniformMatrix3fv_ENUM,                             "glUniformMatrix3fv",                             egl3_uniformMatrix3fv },
{ glUniformMatrix4fv_ENUM,                             "glUniformMatrix4fv",                             egl3_uniformMatrix4fv },
{ glValidateProgram_ENUM,                              "glValidateProgram",                              egl3_validateProgram },
{ glVertexAttrib1d_ENUM,                               "glVertexAttrib1d",                               egl3_vertexAttrib1d },
{ glVertexAttrib1dv_ENUM,                              "glVertexAttrib1dv",                              egl3_vertexAttrib1dv },
{ glVertexAttrib1f_ENUM,                               "glVertexAttrib1f",                               egl3_vertexAttrib1f },
{ glVertexAttrib1fv_ENUM,                              "glVertexAttrib1fv",                              egl3_vertexAttrib1fv },
{ glVertexAttrib1s_ENUM,                               "glVertexAttrib1s",                               egl3_vertexAttrib1s },
{ glVertexAttrib1sv_ENUM,                              "glVertexAttrib1sv",                              egl3_vertexAttrib1sv },
{ glVertexAttrib2d_ENUM,                               "glVertexAttrib2d",                               egl3_vertexAttrib2d },
{ glVertexAttrib2dv_ENUM,                              "glVertexAttrib2dv",                              egl3_vertexAttrib2dv },
{ glVertexAttrib2f_ENUM,                               "glVertexAttrib2f",                               egl3_vertexAttrib2f },
{ glVertexAttrib2fv_ENUM,                              "glVertexAttrib2fv",                              egl3_vertexAttrib2fv },
{ glVertexAttrib2s_ENUM,                               "glVertexAttrib2s",                               egl3_vertexAttrib2s },
{ glVertexAttrib2sv_ENUM,                              "glVertexAttrib2sv",                              egl3_vertexAttrib2sv },
{ glVertexAttrib3d_ENUM,                               "glVertexAttrib3d",                               egl3_vertexAttrib3d },
{ glVertexAttrib3dv_ENUM,                              "glVertexAttrib3dv",                              egl3_vertexAttrib3dv },
{ glVertexAttrib3f_ENUM,                               "glVertexAttrib3f",                               egl3_vertexAttrib3f },
{ glVertexAttrib3fv_ENUM,                              "glVertexAttrib3fv",                              egl3_vertexAttrib3fv },
{ glVertexAttrib3s_ENUM,                               "glVertexAttrib3s",                               egl3_vertexAttrib3s },
{ glVertexAttrib3sv_ENUM,                              "glVertexAttrib3sv",                              egl3_vertexAttrib3sv },
{ glVertexAttrib4Nbv_ENUM,                             "glVertexAttrib4Nbv",                             egl3_vertexAttrib4Nbv },
{ glVertexAttrib4Niv_ENUM,                             "glVertexAttrib4Niv",                             egl3_vertexAttrib4Niv },
{ glVertexAttrib4Nsv_ENUM,                             "glVertexAttrib4Nsv",                             egl3_vertexAttrib4Nsv },
{ glVertexAttrib4Nub_ENUM,                             "glVertexAttrib4Nub",                             egl3_vertexAttrib4Nub },
{ glVertexAttrib4Nubv_ENUM,                            "glVertexAttrib4Nubv",                            egl3_vertexAttrib4Nubv },
{ glVertexAttrib4Nuiv_ENUM,                            "glVertexAttrib4Nuiv",                            egl3_vertexAttrib4Nuiv },
{ glVertexAttrib4Nusv_ENUM,                            "glVertexAttrib4Nusv",                            egl3_vertexAttrib4Nusv },
{ glVertexAttrib4bv_ENUM,                              "glVertexAttrib4bv",                              egl3_vertexAttrib4bv },
{ glVertexAttrib4d_ENUM,                               "glVertexAttrib4d",                               egl3_vertexAttrib4d },
{ glVertexAttrib4dv_ENUM,                              "glVertexAttrib4dv",                              egl3_vertexAttrib4dv },
{ glVertexAttrib4f_ENUM,                               "glVertexAttrib4f",                               egl3_vertexAttrib4f },
{ glVertexAttrib4fv_ENUM,                              "glVertexAttrib4fv",                              egl3_vertexAttrib4fv },
{ glVertexAttrib4iv_ENUM,                              "glVertexAttrib4iv",                              egl3_vertexAttrib4iv },
{ glVertexAttrib4s_ENUM,                               "glVertexAttrib4s",                               egl3_vertexAttrib4s },
{ glVertexAttrib4sv_ENUM,                              "glVertexAttrib4sv",                              egl3_vertexAttrib4sv },
{ glVertexAttrib4ubv_ENUM,                             "glVertexAttrib4ubv",                             egl3_vertexAttrib4ubv },
{ glVertexAttrib4uiv_ENUM,                             "glVertexAttrib4uiv",                             egl3_vertexAttrib4uiv },
{ glVertexAttrib4usv_ENUM,                             "glVertexAttrib4usv",                             egl3_vertexAttrib4usv },
{ glVertexAttribPointer_ENUM,                          "glVertexAttribPointer",                          egl3_vertexAttribPointer },
/* GL_VERSION_2_1 */
{ glUniformMatrix2x3fv_ENUM,                           "glUniformMatrix2x3fv",                           egl3_uniformMatrix2x3fv },
{ glUniformMatrix3x2fv_ENUM,                           "glUniformMatrix3x2fv",                           egl3_uniformMatrix3x2fv },
{ glUniformMatrix2x4fv_ENUM,                           "glUniformMatrix2x4fv",                           egl3_uniformMatrix2x4fv },
{ glUniformMatrix4x2fv_ENUM,                           "glUniformMatrix4x2fv",                           egl3_uniformMatrix4x2fv },
{ glUniformMatrix3x4fv_ENUM,                           "glUniformMatrix3x4fv",                           egl3_uniformMatrix3x4fv },
{ glUniformMatrix4x3fv_ENUM,                           "glUniformMatrix4x3fv",                           egl3_uniformMatrix4x3fv },
/* GL_VERSION_3_0 */
{ glColorMaski_ENUM,                                   "glColorMaski",                                   egl3_colorMaski },
{ glGetBooleani_v_ENUM,                                "glGetBooleani_v",                                egl3_getBooleani_v },
{ glGetIntegeri_v_ENUM,                                "glGetIntegeri_v",                                egl3_getIntegeri_v },
{ glEnablei_ENUM,                                      "glEnablei",                                      egl3_enablei },
{ glDisablei_ENUM,                                     "glDisablei",                                     egl3_disablei },
{ glIsEnabledi_ENUM,                                   "glIsEnabledi",                                   egl3_isEnabledi },
{ glBeginTransformFeedback_ENUM,                       "glBeginTransformFeedback",                       egl3_beginTransformFeedback },
{ glEndTransformFeedback_ENUM,                         "glEndTransformFeedback",                         egl3_endTransformFeedback },
{ glBindBufferRange_ENUM,                              "glBindBufferRange",                              egl3_bindBufferRange },
{ glBindBufferBase_ENUM,                               "glBindBufferBase",                               egl3_bindBufferBase },
{ glTransformFeedbackVaryings_ENUM,                    "glTransformFeedbackVaryings",                    egl3_transformFeedbackVaryings },
{ glGetTransformFeedbackVarying_ENUM,                  "glGetTransformFeedbackVarying",                  egl3_getTransformFeedbackVarying },
{ glClampColor_ENUM,                                   "glClampColor",                                   egl3_clampColor },
{ glBeginConditionalRender_ENUM,                       "glBeginConditionalRender",                       egl3_beginConditionalRender },
{ glEndConditionalRender_ENUM,                         "glEndConditionalRender",                         egl3_endConditionalRender },
{ glVertexAttribIPointer_ENUM,                         "glVertexAttribIPointer",                         egl3_vertexAttribIPointer },
{ glGetVertexAttribIiv_ENUM,                           "glGetVertexAttribIiv",                           egl3_getVertexAttribIiv },
{ glGetVertexAttribIuiv_ENUM,                          "glGetVertexAttribIuiv",                          egl3_getVertexAttribIuiv },
{ glVertexAttribI1i_ENUM,                              "glVertexAttribI1i",                              egl3_vertexAttribI1i },
{ glVertexAttribI2i_ENUM,                              "glVertexAttribI2i",                              egl3_vertexAttribI2i },
{ glVertexAttribI3i_ENUM,                              "glVertexAttribI3i",                              egl3_vertexAttribI3i },
{ glVertexAttribI4i_ENUM,                              "glVertexAttribI4i",                              egl3_vertexAttribI4i },
{ glVertexAttribI1ui_ENUM,                             "glVertexAttribI1ui",                             egl3_vertexAttribI1ui },
{ glVertexAttribI2ui_ENUM,                             "glVertexAttribI2ui",                             egl3_vertexAttribI2ui },
{ glVertexAttribI3ui_ENUM,                             "glVertexAttribI3ui",                             egl3_vertexAttribI3ui },
{ glVertexAttribI4ui_ENUM,                             "glVertexAttribI4ui",                             egl3_vertexAttribI4ui },
{ glVertexAttribI1iv_ENUM,                             "glVertexAttribI1iv",                             egl3_vertexAttribI1iv },
{ glVertexAttribI2iv_ENUM,                             "glVertexAttribI2iv",                             egl3_vertexAttribI2iv },
{ glVertexAttribI3iv_ENUM,                             "glVertexAttribI3iv",                             egl3_vertexAttribI3iv },
{ glVertexAttribI4iv_ENUM,                             "glVertexAttribI4iv",                             egl3_vertexAttribI4iv },
{ glVertexAttribI1uiv_ENUM,                            "glVertexAttribI1uiv",                            egl3_vertexAttribI1uiv },
{ glVertexAttribI2uiv_ENUM,                            "glVertexAttribI2uiv",                            egl3_vertexAttribI2uiv },
{ glVertexAttribI3uiv_ENUM,                            "glVertexAttribI3uiv",                            egl3_vertexAttribI3uiv },
{ glVertexAttribI4uiv_ENUM,                            "glVertexAttribI4uiv",                            egl3_vertexAttribI4uiv },
{ glVertexAttribI4bv_ENUM,                             "glVertexAttribI4bv",                             egl3_vertexAttribI4bv },
{ glVertexAttribI4sv_ENUM,                             "glVertexAttribI4sv",                             egl3_vertexAttribI4sv },
{ glVertexAttribI4ubv_ENUM,                            "glVertexAttribI4ubv",                            egl3_vertexAttribI4ubv },
{ glVertexAttribI4usv_ENUM,                            "glVertexAttribI4usv",                            egl3_vertexAttribI4usv },
{ glGetUniformuiv_ENUM,                                "glGetUniformuiv",                                egl3_getUniformuiv },
{ glBindFragDataLocation_ENUM,                         "glBindFragDataLocation",                         egl3_bindFragDataLocation },
{ glGetFragDataLocation_ENUM,                          "glGetFragDataLocation",                          egl3_getFragDataLocation },
{ glUniform1ui_ENUM,                                   "glUniform1ui",                                   egl3_uniform1ui },
{ glUniform2ui_ENUM,                                   "glUniform2ui",                                   egl3_uniform2ui },
{ glUniform3ui_ENUM,                                   "glUniform3ui",                                   egl3_uniform3ui },
{ glUniform4ui_ENUM,                                   "glUniform4ui",                                   egl3_uniform4ui },
{ glUniform1uiv_ENUM,                                  "glUniform1uiv",                                  egl3_uniform1uiv },
{ glUniform2uiv_ENUM,                                  "glUniform2uiv",                                  egl3_uniform2uiv },
{ glUniform3uiv_ENUM,                                  "glUniform3uiv",                                  egl3_uniform3uiv },
{ glUniform4uiv_ENUM,                                  "glUniform4uiv",                                  egl3_uniform4uiv },
{ glTexParameterIiv_ENUM,                              "glTexParameterIiv",                              egl3_texParameterIiv },
{ glTexParameterIuiv_ENUM,                             "glTexParameterIuiv",                             egl3_texParameterIuiv },
{ glGetTexParameterIiv_ENUM,                           "glGetTexParameterIiv",                           egl3_getTexParameterIiv },
{ glGetTexParameterIuiv_ENUM,                          "glGetTexParameterIuiv",                          egl3_getTexParameterIuiv },
{ glClearBufferiv_ENUM,                                "glClearBufferiv",                                egl3_clearBufferiv },
{ glClearBufferuiv_ENUM,                               "glClearBufferuiv",                               egl3_clearBufferuiv },
{ glClearBufferfv_ENUM,                                "glClearBufferfv",                                egl3_clearBufferfv },
{ glClearBufferfi_ENUM,                                "glClearBufferfi",                                egl3_clearBufferfi },
{ glGetStringi_ENUM,                                   "glGetStringi",                                   egl3_getStringi },
/* GL_VERSION_3_1 */
{ glDrawArraysInstanced_ENUM,                          "glDrawArraysInstanced",                          egl3_drawArraysInstanced },
{ glDrawElementsInstanced_ENUM,                        "glDrawElementsInstanced",                        egl3_drawElementsInstanced },
{ glTexBuffer_ENUM,                                    "glTexBuffer",                                    egl3_texBuffer },
{ glPrimitiveRestartIndex_ENUM,                        "glPrimitiveRestartIndex",                        egl3_primitiveRestartIndex },
/* GL_VERSION_3_2 */
{ glGetInteger64i_v_ENUM,                              "glGetInteger64i_v",                              egl3_getInteger64i_v },
{ glGetBufferParameteri64v_ENUM,                       "glGetBufferParameteri64v",                       egl3_getBufferParameteri64v },
{ glFramebufferTexture_ENUM,                           "glFramebufferTexture",                           egl3_framebufferTexture },
/* GL_VERSION_3_3 */
{ glVertexAttribDivisor_ENUM,                          "glVertexAttribDivisor",                          egl3_vertexAttribDivisor },
/* GL_VERSION_4_0 */
{ glMinSampleShading_ENUM,                             "glMinSampleShading",                             egl3_minSampleShading },
{ glBlendEquationi_ENUM,                               "glBlendEquationi",                               egl3_blendEquationi },
{ glBlendEquationSeparatei_ENUM,                       "glBlendEquationSeparatei",                       egl3_blendEquationSeparatei },
{ glBlendFunci_ENUM,                                   "glBlendFunci",                                   egl3_blendFunci },
{ glBlendFuncSeparatei_ENUM,                           "glBlendFuncSeparatei",                           egl3_blendFuncSeparatei },
/* GL_VERSION_4_1 */
/* GL_ARB_depth_buffer_float */
/* GL_ARB_framebuffer_object */
{ glIsRenderbuffer_ENUM,                               "glIsRenderbuffer",                               egl3_isRenderbuffer },
{ glBindRenderbuffer_ENUM,                             "glBindRenderbuffer",                             egl3_bindRenderbuffer },
{ glDeleteRenderbuffers_ENUM,                          "glDeleteRenderbuffers",                          egl3_deleteRenderbuffers },
{ glGenRenderbuffers_ENUM,                             "glGenRenderbuffers",                             egl3_genRenderbuffers },
{ glRenderbufferStorage_ENUM,                          "glRenderbufferStorage",                          egl3_renderbufferStorage },
{ glGetRenderbufferParameteriv_ENUM,                   "glGetRenderbufferParameteriv",                   egl3_getRenderbufferParameteriv },
{ glIsFramebuffer_ENUM,                                "glIsFramebuffer",                                egl3_isFramebuffer },
{ glBindFramebuffer_ENUM,                              "glBindFramebuffer",                              egl3_bindFramebuffer },
{ glDeleteFramebuffers_ENUM,                           "glDeleteFramebuffers",                           egl3_deleteFramebuffers },
{ glGenFramebuffers_ENUM,                              "glGenFramebuffers",                              egl3_genFramebuffers },
{ glCheckFramebufferStatus_ENUM,                       "glCheckFramebufferStatus",                       egl3_checkFramebufferStatus },
{ glFramebufferTexture1D_ENUM,                         "glFramebufferTexture1D",                         egl3_framebufferTexture1D },
{ glFramebufferTexture2D_ENUM,                         "glFramebufferTexture2D",                         egl3_framebufferTexture2D },
{ glFramebufferTexture3D_ENUM,                         "glFramebufferTexture3D",                         egl3_framebufferTexture3D },
{ glFramebufferRenderbuffer_ENUM,                      "glFramebufferRenderbuffer",                      egl3_framebufferRenderbuffer },
{ glGetFramebufferAttachmentParameteriv_ENUM,          "glGetFramebufferAttachmentParameteriv",          egl3_getFramebufferAttachmentParameteriv },
{ glGenerateMipmap_ENUM,                               "glGenerateMipmap",                               egl3_generateMipmap },
{ glBlitFramebuffer_ENUM,                              "glBlitFramebuffer",                              egl3_blitFramebuffer },
{ glRenderbufferStorageMultisample_ENUM,               "glRenderbufferStorageMultisample",               egl3_renderbufferStorageMultisample },
{ glFramebufferTextureLayer_ENUM,                      "glFramebufferTextureLayer",                      egl3_framebufferTextureLayer },
/* GL_ARB_map_buffer_range */
{ glMapBufferRange_ENUM,                               "glMapBufferRange",                               egl3_mapBufferRange },
{ glFlushMappedBufferRange_ENUM,                       "glFlushMappedBufferRange",                       egl3_flushMappedBufferRange },
/* GL_ARB_vertex_array_object */
{ glBindVertexArray_ENUM,                              "glBindVertexArray",                              egl3_bindVertexArray },
{ glDeleteVertexArrays_ENUM,                           "glDeleteVertexArrays",                           egl3_deleteVertexArrays },
{ glGenVertexArrays_ENUM,                              "glGenVertexArrays",                              egl3_genVertexArrays },
{ glIsVertexArray_ENUM,                                "glIsVertexArray",                                egl3_isVertexArray },
/* GL_ARB_uniform_buffer_object */
{ glGetUniformIndices_ENUM,                            "glGetUniformIndices",                            egl3_getUniformIndices },
{ glGetActiveUniformsiv_ENUM,                          "glGetActiveUniformsiv",                          egl3_getActiveUniformsiv },
{ glGetActiveUniformName_ENUM,                         "glGetActiveUniformName",                         egl3_getActiveUniformName },
{ glGetUniformBlockIndex_ENUM,                         "glGetUniformBlockIndex",                         egl3_getUniformBlockIndex },
{ glGetActiveUniformBlockiv_ENUM,                      "glGetActiveUniformBlockiv",                      egl3_getActiveUniformBlockiv },
{ glGetActiveUniformBlockName_ENUM,                    "glGetActiveUniformBlockName",                    egl3_getActiveUniformBlockName },
{ glUniformBlockBinding_ENUM,                          "glUniformBlockBinding",                          egl3_uniformBlockBinding },
/* GL_ARB_copy_buffer */
{ glCopyBufferSubData_ENUM,                            "glCopyBufferSubData",                            egl3_copyBufferSubData },
/* GL_ARB_draw_elements_base_vertex */
{ glDrawElementsBaseVertex_ENUM,                       "glDrawElementsBaseVertex",                       egl3_drawElementsBaseVertex },
{ glDrawRangeElementsBaseVertex_ENUM,                  "glDrawRangeElementsBaseVertex",                  egl3_drawRangeElementsBaseVertex },
{ glDrawElementsInstancedBaseVertex_ENUM,              "glDrawElementsInstancedBaseVertex",              egl3_drawElementsInstancedBaseVertex },
{ glMultiDrawElementsBaseVertex_ENUM,                  "glMultiDrawElementsBaseVertex",                  egl3_multiDrawElementsBaseVertex },
/* GL_ARB_provoking_vertex */
{ glProvokingVertex_ENUM,                              "glProvokingVertex",                              egl3_provokingVertex },
/* GL_ARB_sync */
{ glFenceSync_ENUM,                                    "glFenceSync",                                    egl3_fenceSync },
{ glIsSync_ENUM,                                       "glIsSync",                                       egl3_isSync },
{ glDeleteSync_ENUM,                                   "glDeleteSync",                                   egl3_deleteSync },
{ glClientWaitSync_ENUM,                               "glClientWaitSync",                               egl3_clientWaitSync },
{ glWaitSync_ENUM,                                     "glWaitSync",                                     egl3_waitSync },
{ glGetInteger64v_ENUM,                                "glGetInteger64v",                                egl3_getInteger64v },
{ glGetSynciv_ENUM,                                    "glGetSynciv",                                    egl3_getSynciv },
/* GL_ARB_texture_multisample */
{ glTexImage2DMultisample_ENUM,                        "glTexImage2DMultisample",                        egl3_texImage2DMultisample },
{ glTexImage3DMultisample_ENUM,                        "glTexImage3DMultisample",                        egl3_texImage3DMultisample },
{ glGetMultisamplefv_ENUM,                             "glGetMultisamplefv",                             egl3_getMultisamplefv },
{ glSampleMaski_ENUM,                                  "glSampleMaski",                                  egl3_sampleMaski },
/* GL_ARB_draw_buffers_blend */
{ glBlendEquationiARB_ENUM,                            "glBlendEquationiARB",                            egl3_blendEquationiARB },
{ glBlendEquationSeparateiARB_ENUM,                    "glBlendEquationSeparateiARB",                    egl3_blendEquationSeparateiARB },
{ glBlendFunciARB_ENUM,                                "glBlendFunciARB",                                egl3_blendFunciARB },
{ glBlendFuncSeparateiARB_ENUM,                        "glBlendFuncSeparateiARB",                        egl3_blendFuncSeparateiARB },
/* GL_ARB_sample_shading */
{ glMinSampleShadingARB_ENUM,                          "glMinSampleShadingARB",                          egl3_minSampleShadingARB },
/* GL_ARB_texture_cube_map_array */
/* GL_ARB_texture_gather */
/* GL_ARB_texture_query_lod */
/* GL_ARB_shading_language_include */
{ glNamedStringARB_ENUM,                               "glNamedStringARB",                               egl3_namedStringARB },
{ glDeleteNamedStringARB_ENUM,                         "glDeleteNamedStringARB",                         egl3_deleteNamedStringARB },
{ glCompileShaderIncludeARB_ENUM,                      "glCompileShaderIncludeARB",                      egl3_compileShaderIncludeARB },
{ glIsNamedStringARB_ENUM,                             "glIsNamedStringARB",                             egl3_isNamedStringARB },
{ glGetNamedStringARB_ENUM,                            "glGetNamedStringARB",                            egl3_getNamedStringARB },
{ glGetNamedStringivARB_ENUM,                          "glGetNamedStringivARB",                          egl3_getNamedStringivARB },
/* GL_ARB_texture_compression_bptc */
/* GL_ARB_blend_func_extended */
{ glBindFragDataLocationIndexed_ENUM,                  "glBindFragDataLocationIndexed",                  egl3_bindFragDataLocationIndexed },
{ glGetFragDataIndex_ENUM,                             "glGetFragDataIndex",                             egl3_getFragDataIndex },
/* GL_ARB_explicit_attrib_location */
/* GL_ARB_occlusion_query2 */
/* GL_ARB_sampler_objects */
{ glGenSamplers_ENUM,                                  "glGenSamplers",                                  egl3_genSamplers },
{ glDeleteSamplers_ENUM,                               "glDeleteSamplers",                               egl3_deleteSamplers },
{ glIsSampler_ENUM,                                    "glIsSampler",                                    egl3_isSampler },
{ glBindSampler_ENUM,                                  "glBindSampler",                                  egl3_bindSampler },
{ glSamplerParameteri_ENUM,                            "glSamplerParameteri",                            egl3_samplerParameteri },
{ glSamplerParameteriv_ENUM,                           "glSamplerParameteriv",                           egl3_samplerParameteriv },
{ glSamplerParameterf_ENUM,                            "glSamplerParameterf",                            egl3_samplerParameterf },
{ glSamplerParameterfv_ENUM,                           "glSamplerParameterfv",                           egl3_samplerParameterfv },
{ glSamplerParameterIiv_ENUM,                          "glSamplerParameterIiv",                          egl3_samplerParameterIiv },
{ glSamplerParameterIuiv_ENUM,                         "glSamplerParameterIuiv",                         egl3_samplerParameterIuiv },
{ glGetSamplerParameteriv_ENUM,                        "glGetSamplerParameteriv",                        egl3_getSamplerParameteriv },
{ glGetSamplerParameterIiv_ENUM,                       "glGetSamplerParameterIiv",                       egl3_getSamplerParameterIiv },
{ glGetSamplerParameterfv_ENUM,                        "glGetSamplerParameterfv",                        egl3_getSamplerParameterfv },
{ glGetSamplerParameterIuiv_ENUM,                      "glGetSamplerParameterIuiv",                      egl3_getSamplerParameterIuiv },
/* GL_ARB_texture_rgb10_a2ui */
/* GL_ARB_texture_swizzle */
/* GL_ARB_timer_query */
{ glQueryCounter_ENUM,                                 "glQueryCounter",                                 egl3_queryCounter },
{ glGetQueryObjecti64v_ENUM,                           "glGetQueryObjecti64v",                           egl3_getQueryObjecti64v },
{ glGetQueryObjectui64v_ENUM,                          "glGetQueryObjectui64v",                          egl3_getQueryObjectui64v },
/* GL_ARB_vertex_type_2_10_10_10_rev */
{ glVertexP2ui_ENUM,                                   "glVertexP2ui",                                   egl3_vertexP2ui },
{ glVertexP2uiv_ENUM,                                  "glVertexP2uiv",                                  egl3_vertexP2uiv },
{ glVertexP3ui_ENUM,                                   "glVertexP3ui",                                   egl3_vertexP3ui },
{ glVertexP3uiv_ENUM,                                  "glVertexP3uiv",                                  egl3_vertexP3uiv },
{ glVertexP4ui_ENUM,                                   "glVertexP4ui",                                   egl3_vertexP4ui },
{ glVertexP4uiv_ENUM,                                  "glVertexP4uiv",                                  egl3_vertexP4uiv },
{ glTexCoordP1ui_ENUM,                                 "glTexCoordP1ui",                                 egl3_texCoordP1ui },
{ glTexCoordP1uiv_ENUM,                                "glTexCoordP1uiv",                                egl3_texCoordP1uiv },
{ glTexCoordP2ui_ENUM,                                 "glTexCoordP2ui",                                 egl3_texCoordP2ui },
{ glTexCoordP2uiv_ENUM,                                "glTexCoordP2uiv",                                egl3_texCoordP2uiv },
{ glTexCoordP3ui_ENUM,                                 "glTexCoordP3ui",                                 egl3_texCoordP3ui },
{ glTexCoordP3uiv_ENUM,                                "glTexCoordP3uiv",                                egl3_texCoordP3uiv },
{ glTexCoordP4ui_ENUM,                                 "glTexCoordP4ui",                                 egl3_texCoordP4ui },
{ glTexCoordP4uiv_ENUM,                                "glTexCoordP4uiv",                                egl3_texCoordP4uiv },
{ glMultiTexCoordP1ui_ENUM,                            "glMultiTexCoordP1ui",                            egl3_multiTexCoordP1ui },
{ glMultiTexCoordP1uiv_ENUM,                           "glMultiTexCoordP1uiv",                           egl3_multiTexCoordP1uiv },
{ glMultiTexCoordP2ui_ENUM,                            "glMultiTexCoordP2ui",                            egl3_multiTexCoordP2ui },
{ glMultiTexCoordP2uiv_ENUM,                           "glMultiTexCoordP2uiv",                           egl3_multiTexCoordP2uiv },
{ glMultiTexCoordP3ui_ENUM,                            "glMultiTexCoordP3ui",                            egl3_multiTexCoordP3ui },
{ glMultiTexCoordP3uiv_ENUM,                           "glMultiTexCoordP3uiv",                           egl3_multiTexCoordP3uiv },
{ glMultiTexCoordP4ui_ENUM,                            "glMultiTexCoordP4ui",                            egl3_multiTexCoordP4ui },
{ glMultiTexCoordP4uiv_ENUM,                           "glMultiTexCoordP4uiv",                           egl3_multiTexCoordP4uiv },
{ glNormalP3ui_ENUM,                                   "glNormalP3ui",                                   egl3_normalP3ui },
{ glNormalP3uiv_ENUM,                                  "glNormalP3uiv",                                  egl3_normalP3uiv },
{ glColorP3ui_ENUM,                                    "glColorP3ui",                                    egl3_colorP3ui },
{ glColorP3uiv_ENUM,                                   "glColorP3uiv",                                   egl3_colorP3uiv },
{ glColorP4ui_ENUM,                                    "glColorP4ui",                                    egl3_colorP4ui },
{ glColorP4uiv_ENUM,                                   "glColorP4uiv",                                   egl3_colorP4uiv },
{ glSecondaryColorP3ui_ENUM,                           "glSecondaryColorP3ui",                           egl3_secondaryColorP3ui },
{ glSecondaryColorP3uiv_ENUM,                          "glSecondaryColorP3uiv",                          egl3_secondaryColorP3uiv },
{ glVertexAttribP1ui_ENUM,                             "glVertexAttribP1ui",                             egl3_vertexAttribP1ui },
{ glVertexAttribP1uiv_ENUM,                            "glVertexAttribP1uiv",                            egl3_vertexAttribP1uiv },
{ glVertexAttribP2ui_ENUM,                             "glVertexAttribP2ui",                             egl3_vertexAttribP2ui },
{ glVertexAttribP2uiv_ENUM,                            "glVertexAttribP2uiv",                            egl3_vertexAttribP2uiv },
{ glVertexAttribP3ui_ENUM,                             "glVertexAttribP3ui",                             egl3_vertexAttribP3ui },
{ glVertexAttribP3uiv_ENUM,                            "glVertexAttribP3uiv",                            egl3_vertexAttribP3uiv },
{ glVertexAttribP4ui_ENUM,                             "glVertexAttribP4ui",                             egl3_vertexAttribP4ui },
{ glVertexAttribP4uiv_ENUM,                            "glVertexAttribP4uiv",                            egl3_vertexAttribP4uiv },
/* GL_ARB_draw_indirect */
{ glDrawArraysIndirect_ENUM,                           "glDrawArraysIndirect",                           egl3_drawArraysIndirect },
{ glDrawElementsIndirect_ENUM,                         "glDrawElementsIndirect",                         egl3_drawElementsIndirect },
/* GL_ARB_gpu_shader5 */
/* GL_ARB_gpu_shader_fp64 */
{ glUniform1d_ENUM,                                    "glUniform1d",                                    egl3_uniform1d },
{ glUniform2d_ENUM,                                    "glUniform2d",                                    egl3_uniform2d },
{ glUniform3d_ENUM,                                    "glUniform3d",                                    egl3_uniform3d },
{ glUniform4d_ENUM,                                    "glUniform4d",                                    egl3_uniform4d },
{ glUniform1dv_ENUM,                                   "glUniform1dv",                                   egl3_uniform1dv },
{ glUniform2dv_ENUM,                                   "glUniform2dv",                                   egl3_uniform2dv },
{ glUniform3dv_ENUM,                                   "glUniform3dv",                                   egl3_uniform3dv },
{ glUniform4dv_ENUM,                                   "glUniform4dv",                                   egl3_uniform4dv },
{ glUniformMatrix2dv_ENUM,                             "glUniformMatrix2dv",                             egl3_uniformMatrix2dv },
{ glUniformMatrix3dv_ENUM,                             "glUniformMatrix3dv",                             egl3_uniformMatrix3dv },
{ glUniformMatrix4dv_ENUM,                             "glUniformMatrix4dv",                             egl3_uniformMatrix4dv },
{ glUniformMatrix2x3dv_ENUM,                           "glUniformMatrix2x3dv",                           egl3_uniformMatrix2x3dv },
{ glUniformMatrix2x4dv_ENUM,                           "glUniformMatrix2x4dv",                           egl3_uniformMatrix2x4dv },
{ glUniformMatrix3x2dv_ENUM,                           "glUniformMatrix3x2dv",                           egl3_uniformMatrix3x2dv },
{ glUniformMatrix3x4dv_ENUM,                           "glUniformMatrix3x4dv",                           egl3_uniformMatrix3x4dv },
{ glUniformMatrix4x2dv_ENUM,                           "glUniformMatrix4x2dv",                           egl3_uniformMatrix4x2dv },
{ glUniformMatrix4x3dv_ENUM,                           "glUniformMatrix4x3dv",                           egl3_uniformMatrix4x3dv },
{ glGetUniformdv_ENUM,                                 "glGetUniformdv",                                 egl3_getUniformdv },
/* GL_ARB_shader_subroutine */
{ glGetSubroutineUniformLocation_ENUM,                 "glGetSubroutineUniformLocation",                 egl3_getSubroutineUniformLocation },
{ glGetSubroutineIndex_ENUM,                           "glGetSubroutineIndex",                           egl3_getSubroutineIndex },
{ glGetActiveSubroutineUniformiv_ENUM,                 "glGetActiveSubroutineUniformiv",                 egl3_getActiveSubroutineUniformiv },
{ glGetActiveSubroutineUniformName_ENUM,               "glGetActiveSubroutineUniformName",               egl3_getActiveSubroutineUniformName },
{ glGetActiveSubroutineName_ENUM,                      "glGetActiveSubroutineName",                      egl3_getActiveSubroutineName },
{ glUniformSubroutinesuiv_ENUM,                        "glUniformSubroutinesuiv",                        egl3_uniformSubroutinesuiv },
{ glGetUniformSubroutineuiv_ENUM,                      "glGetUniformSubroutineuiv",                      egl3_getUniformSubroutineuiv },
{ glGetProgramStageiv_ENUM,                            "glGetProgramStageiv",                            egl3_getProgramStageiv },
/* GL_ARB_tessellation_shader */
{ glPatchParameteri_ENUM,                              "glPatchParameteri",                              egl3_patchParameteri },
{ glPatchParameterfv_ENUM,                             "glPatchParameterfv",                             egl3_patchParameterfv },
/* GL_ARB_texture_buffer_object_rgb32 */
/* GL_ARB_transform_feedback2 */
{ glBindTransformFeedback_ENUM,                        "glBindTransformFeedback",                        egl3_bindTransformFeedback },
{ glDeleteTransformFeedbacks_ENUM,                     "glDeleteTransformFeedbacks",                     egl3_deleteTransformFeedbacks },
{ glGenTransformFeedbacks_ENUM,                        "glGenTransformFeedbacks",                        egl3_genTransformFeedbacks },
{ glIsTransformFeedback_ENUM,                          "glIsTransformFeedback",                          egl3_isTransformFeedback },
{ glPauseTransformFeedback_ENUM,                       "glPauseTransformFeedback",                       egl3_pauseTransformFeedback },
{ glResumeTransformFeedback_ENUM,                      "glResumeTransformFeedback",                      egl3_resumeTransformFeedback },
{ glDrawTransformFeedback_ENUM,                        "glDrawTransformFeedback",                        egl3_drawTransformFeedback },
/* GL_ARB_transform_feedback3 */
{ glDrawTransformFeedbackStream_ENUM,                  "glDrawTransformFeedbackStream",                  egl3_drawTransformFeedbackStream },
{ glBeginQueryIndexed_ENUM,                            "glBeginQueryIndexed",                            egl3_beginQueryIndexed },
{ glEndQueryIndexed_ENUM,                              "glEndQueryIndexed",                              egl3_endQueryIndexed },
{ glGetQueryIndexediv_ENUM,                            "glGetQueryIndexediv",                            egl3_getQueryIndexediv },
/* GL_ARB_ES2_compatibility */
{ glReleaseShaderCompiler_ENUM,                        "glReleaseShaderCompiler",                        egl3_releaseShaderCompiler },
{ glShaderBinary_ENUM,                                 "glShaderBinary",                                 egl3_shaderBinary },
{ glGetShaderPrecisionFormat_ENUM,                     "glGetShaderPrecisionFormat",                     egl3_getShaderPrecisionFormat },
{ glDepthRangef_ENUM,                                  "glDepthRangef",                                  egl3_depthRangef },
{ glClearDepthf_ENUM,                                  "glClearDepthf",                                  egl3_clearDepthf },
/* GL_ARB_get_program_binary */
{ glGetProgramBinary_ENUM,                             "glGetProgramBinary",                             egl3_getProgramBinary },
{ glProgramBinary_ENUM,                                "glProgramBinary",                                egl3_programBinary },
{ glProgramParameteri_ENUM,                            "glProgramParameteri",                            egl3_programParameteri },
/* GL_ARB_separate_shader_objects */
{ glUseProgramStages_ENUM,                             "glUseProgramStages",                             egl3_useProgramStages },
{ glActiveShaderProgram_ENUM,                          "glActiveShaderProgram",                          egl3_activeShaderProgram },
{ glCreateShaderProgramv_ENUM,                         "glCreateShaderProgramv",                         egl3_createShaderProgramv },
{ glBindProgramPipeline_ENUM,                          "glBindProgramPipeline",                          egl3_bindProgramPipeline },
{ glDeleteProgramPipelines_ENUM,                       "glDeleteProgramPipelines",                       egl3_deleteProgramPipelines },
{ glGenProgramPipelines_ENUM,                          "glGenProgramPipelines",                          egl3_genProgramPipelines },
{ glIsProgramPipeline_ENUM,                            "glIsProgramPipeline",                            egl3_isProgramPipeline },
{ glGetProgramPipelineiv_ENUM,                         "glGetProgramPipelineiv",                         egl3_getProgramPipelineiv },
{ glProgramUniform1i_ENUM,                             "glProgramUniform1i",                             egl3_programUniform1i },
{ glProgramUniform1iv_ENUM,                            "glProgramUniform1iv",                            egl3_programUniform1iv },
{ glProgramUniform1f_ENUM,                             "glProgramUniform1f",                             egl3_programUniform1f },
{ glProgramUniform1fv_ENUM,                            "glProgramUniform1fv",                            egl3_programUniform1fv },
{ glProgramUniform1d_ENUM,                             "glProgramUniform1d",                             egl3_programUniform1d },
{ glProgramUniform1dv_ENUM,                            "glProgramUniform1dv",                            egl3_programUniform1dv },
{ glProgramUniform1ui_ENUM,                            "glProgramUniform1ui",                            egl3_programUniform1ui },
{ glProgramUniform1uiv_ENUM,                           "glProgramUniform1uiv",                           egl3_programUniform1uiv },
{ glProgramUniform2i_ENUM,                             "glProgramUniform2i",                             egl3_programUniform2i },
{ glProgramUniform2iv_ENUM,                            "glProgramUniform2iv",                            egl3_programUniform2iv },
{ glProgramUniform2f_ENUM,                             "glProgramUniform2f",                             egl3_programUniform2f },
{ glProgramUniform2fv_ENUM,                            "glProgramUniform2fv",                            egl3_programUniform2fv },
{ glProgramUniform2d_ENUM,                             "glProgramUniform2d",                             egl3_programUniform2d },
{ glProgramUniform2dv_ENUM,                            "glProgramUniform2dv",                            egl3_programUniform2dv },
{ glProgramUniform2ui_ENUM,                            "glProgramUniform2ui",                            egl3_programUniform2ui },
{ glProgramUniform2uiv_ENUM,                           "glProgramUniform2uiv",                           egl3_programUniform2uiv },
{ glProgramUniform3i_ENUM,                             "glProgramUniform3i",                             egl3_programUniform3i },
{ glProgramUniform3iv_ENUM,                            "glProgramUniform3iv",                            egl3_programUniform3iv },
{ glProgramUniform3f_ENUM,                             "glProgramUniform3f",                             egl3_programUniform3f },
{ glProgramUniform3fv_ENUM,                            "glProgramUniform3fv",                            egl3_programUniform3fv },
{ glProgramUniform3d_ENUM,                             "glProgramUniform3d",                             egl3_programUniform3d },
{ glProgramUniform3dv_ENUM,                            "glProgramUniform3dv",                            egl3_programUniform3dv },
{ glProgramUniform3ui_ENUM,                            "glProgramUniform3ui",                            egl3_programUniform3ui },
{ glProgramUniform3uiv_ENUM,                           "glProgramUniform3uiv",                           egl3_programUniform3uiv },
{ glProgramUniform4i_ENUM,                             "glProgramUniform4i",                             egl3_programUniform4i },
{ glProgramUniform4iv_ENUM,                            "glProgramUniform4iv",                            egl3_programUniform4iv },
{ glProgramUniform4f_ENUM,                             "glProgramUniform4f",                             egl3_programUniform4f },
{ glProgramUniform4fv_ENUM,                            "glProgramUniform4fv",                            egl3_programUniform4fv },
{ glProgramUniform4d_ENUM,                             "glProgramUniform4d",                             egl3_programUniform4d },
{ glProgramUniform4dv_ENUM,                            "glProgramUniform4dv",                            egl3_programUniform4dv },
{ glProgramUniform4ui_ENUM,                            "glProgramUniform4ui",                            egl3_programUniform4ui },
{ glProgramUniform4uiv_ENUM,                           "glProgramUniform4uiv",                           egl3_programUniform4uiv },
{ glProgramUniformMatrix2fv_ENUM,                      "glProgramUniformMatrix2fv",                      egl3_programUniformMatrix2fv },
{ glProgramUniformMatrix3fv_ENUM,                      "glProgramUniformMatrix3fv",                      egl3_programUniformMatrix3fv },
{ glProgramUniformMatrix4fv_ENUM,                      "glProgramUniformMatrix4fv",                      egl3_programUniformMatrix4fv },
{ glProgramUniformMatrix2dv_ENUM,                      "glProgramUniformMatrix2dv",                      egl3_programUniformMatrix2dv },
{ glProgramUniformMatrix3dv_ENUM,                      "glProgramUniformMatrix3dv",                      egl3_programUniformMatrix3dv },
{ glProgramUniformMatrix4dv_ENUM,                      "glProgramUniformMatrix4dv",                      egl3_programUniformMatrix4dv },
{ glProgramUniformMatrix2x3fv_ENUM,                    "glProgramUniformMatrix2x3fv",                    egl3_programUniformMatrix2x3fv },
{ glProgramUniformMatrix3x2fv_ENUM,                    "glProgramUniformMatrix3x2fv",                    egl3_programUniformMatrix3x2fv },
{ glProgramUniformMatrix2x4fv_ENUM,                    "glProgramUniformMatrix2x4fv",                    egl3_programUniformMatrix2x4fv },
{ glProgramUniformMatrix4x2fv_ENUM,                    "glProgramUniformMatrix4x2fv",                    egl3_programUniformMatrix4x2fv },
{ glProgramUniformMatrix3x4fv_ENUM,                    "glProgramUniformMatrix3x4fv",                    egl3_programUniformMatrix3x4fv },
{ glProgramUniformMatrix4x3fv_ENUM,                    "glProgramUniformMatrix4x3fv",                    egl3_programUniformMatrix4x3fv },
{ glProgramUniformMatrix2x3dv_ENUM,                    "glProgramUniformMatrix2x3dv",                    egl3_programUniformMatrix2x3dv },
{ glProgramUniformMatrix3x2dv_ENUM,                    "glProgramUniformMatrix3x2dv",                    egl3_programUniformMatrix3x2dv },
{ glProgramUniformMatrix2x4dv_ENUM,                    "glProgramUniformMatrix2x4dv",                    egl3_programUniformMatrix2x4dv },
{ glProgramUniformMatrix4x2dv_ENUM,                    "glProgramUniformMatrix4x2dv",                    egl3_programUniformMatrix4x2dv },
{ glProgramUniformMatrix3x4dv_ENUM,                    "glProgramUniformMatrix3x4dv",                    egl3_programUniformMatrix3x4dv },
{ glProgramUniformMatrix4x3dv_ENUM,                    "glProgramUniformMatrix4x3dv",                    egl3_programUniformMatrix4x3dv },
{ glValidateProgramPipeline_ENUM,                      "glValidateProgramPipeline",                      egl3_validateProgramPipeline },
{ glGetProgramPipelineInfoLog_ENUM,                    "glGetProgramPipelineInfoLog",                    egl3_getProgramPipelineInfoLog },
/* GL_ARB_vertex_attrib_64bit */
{ glVertexAttribL1d_ENUM,                              "glVertexAttribL1d",                              egl3_vertexAttribL1d },
{ glVertexAttribL2d_ENUM,                              "glVertexAttribL2d",                              egl3_vertexAttribL2d },
{ glVertexAttribL3d_ENUM,                              "glVertexAttribL3d",                              egl3_vertexAttribL3d },
{ glVertexAttribL4d_ENUM,                              "glVertexAttribL4d",                              egl3_vertexAttribL4d },
{ glVertexAttribL1dv_ENUM,                             "glVertexAttribL1dv",                             egl3_vertexAttribL1dv },
{ glVertexAttribL2dv_ENUM,                             "glVertexAttribL2dv",                             egl3_vertexAttribL2dv },
{ glVertexAttribL3dv_ENUM,                             "glVertexAttribL3dv",                             egl3_vertexAttribL3dv },
{ glVertexAttribL4dv_ENUM,                             "glVertexAttribL4dv",                             egl3_vertexAttribL4dv },
{ glVertexAttribLPointer_ENUM,                         "glVertexAttribLPointer",                         egl3_vertexAttribLPointer },
{ glGetVertexAttribLdv_ENUM,                           "glGetVertexAttribLdv",                           egl3_getVertexAttribLdv },
/* GL_ARB_viewport_array */
{ glViewportArrayv_ENUM,                               "glViewportArrayv",                               egl3_viewportArrayv },
{ glViewportIndexedf_ENUM,                             "glViewportIndexedf",                             egl3_viewportIndexedf },
{ glViewportIndexedfv_ENUM,                            "glViewportIndexedfv",                            egl3_viewportIndexedfv },
{ glScissorArrayv_ENUM,                                "glScissorArrayv",                                egl3_scissorArrayv },
{ glScissorIndexed_ENUM,                               "glScissorIndexed",                               egl3_scissorIndexed },
{ glScissorIndexedv_ENUM,                              "glScissorIndexedv",                              egl3_scissorIndexedv },
{ glDepthRangeArrayv_ENUM,                             "glDepthRangeArrayv",                             egl3_depthRangeArrayv },
{ glDepthRangeIndexed_ENUM,                            "glDepthRangeIndexed",                            egl3_depthRangeIndexed },
{ glGetFloati_v_ENUM,                                  "glGetFloati_v",                                  egl3_getFloati_v },
{ glGetDoublei_v_ENUM,                                 "glGetDoublei_v",                                 egl3_getDoublei_v },
/* GL_ARB_cl_event */
{ glCreateSyncFromCLeventARB_ENUM,                     "glCreateSyncFromCLeventARB",                     egl3_createSyncFromCLeventARB },
/* GL_ARB_debug_output */
{ glDebugMessageControlARB_ENUM,                       "glDebugMessageControlARB",                       egl3_debugMessageControlARB },
{ glDebugMessageInsertARB_ENUM,                        "glDebugMessageInsertARB",                        egl3_debugMessageInsertARB },
{ glDebugMessageCallbackARB_ENUM,                      "glDebugMessageCallbackARB",                      egl3_debugMessageCallbackARB },
{ glGetDebugMessageLogARB_ENUM,                        "glGetDebugMessageLogARB",                        egl3_getDebugMessageLogARB },
/* GL_ARB_robustness */
{ glGetGraphicsResetStatusARB_ENUM,                    "glGetGraphicsResetStatusARB",                    egl3_getGraphicsResetStatusARB },
{ glGetnMapdvARB_ENUM,                                 "glGetnMapdvARB",                                 egl3_getnMapdvARB },
{ glGetnMapfvARB_ENUM,                                 "glGetnMapfvARB",                                 egl3_getnMapfvARB },
{ glGetnMapivARB_ENUM,                                 "glGetnMapivARB",                                 egl3_getnMapivARB },
{ glGetnPixelMapfvARB_ENUM,                            "glGetnPixelMapfvARB",                            egl3_getnPixelMapfvARB },
{ glGetnPixelMapuivARB_ENUM,                           "glGetnPixelMapuivARB",                           egl3_getnPixelMapuivARB },
{ glGetnPixelMapusvARB_ENUM,                           "glGetnPixelMapusvARB",                           egl3_getnPixelMapusvARB },
{ glGetnPolygonStippleARB_ENUM,                        "glGetnPolygonStippleARB",                        egl3_getnPolygonStippleARB },
{ glGetnColorTableARB_ENUM,                            "glGetnColorTableARB",                            egl3_getnColorTableARB },
{ glGetnConvolutionFilterARB_ENUM,                     "glGetnConvolutionFilterARB",                     egl3_getnConvolutionFilterARB },
{ glGetnSeparableFilterARB_ENUM,                       "glGetnSeparableFilterARB",                       egl3_getnSeparableFilterARB },
{ glGetnHistogramARB_ENUM,                             "glGetnHistogramARB",                             egl3_getnHistogramARB },
{ glGetnMinmaxARB_ENUM,                                "glGetnMinmaxARB",                                egl3_getnMinmaxARB },
{ glGetnTexImageARB_ENUM,                              "glGetnTexImageARB",                              egl3_getnTexImageARB },
{ glReadnPixelsARB_ENUM,                               "glReadnPixelsARB",                               egl3_readnPixelsARB },
{ glGetnCompressedTexImageARB_ENUM,                    "glGetnCompressedTexImageARB",                    egl3_getnCompressedTexImageARB },
{ glGetnUniformfvARB_ENUM,                             "glGetnUniformfvARB",                             egl3_getnUniformfvARB },
{ glGetnUniformivARB_ENUM,                             "glGetnUniformivARB",                             egl3_getnUniformivARB },
{ glGetnUniformuivARB_ENUM,                            "glGetnUniformuivARB",                            egl3_getnUniformuivARB },
{ glGetnUniformdvARB_ENUM,                             "glGetnUniformdvARB",                             egl3_getnUniformdvARB },
/* GL_ARB_shader_stencil_export */
/* GL_ARB_base_instance */
{ glDrawArraysInstancedBaseInstance_ENUM,              "glDrawArraysInstancedBaseInstance",              egl3_drawArraysInstancedBaseInstance },
{ glDrawElementsInstancedBaseInstance_ENUM,            "glDrawElementsInstancedBaseInstance",            egl3_drawElementsInstancedBaseInstance },
{ glDrawElementsInstancedBaseVertexBaseInstance_ENUM,  "glDrawElementsInstancedBaseVertexBaseInstance",  egl3_drawElementsInstancedBaseVertexBaseInstance },
/* GL_ARB_shading_language_420pack */
/* GL_ARB_transform_feedback_instanced */
{ glDrawTransformFeedbackInstanced_ENUM,               "glDrawTransformFeedbackInstanced",               egl3_drawTransformFeedbackInstanced },
{ glDrawTransformFeedbackStreamInstanced_ENUM,         "glDrawTransformFeedbackStreamInstanced",         egl3_drawTransformFeedbackStreamInstanced },
/* GL_ARB_compressed_texture_pixel_storage */
/* GL_ARB_conservative_depth */
/* GL_ARB_internalformat_query */
{ glGetInternalformativ_ENUM,                          "glGetInternalformativ",                          egl3_getInternalformativ },
/* GL_ARB_map_buffer_alignment */
/* GL_ARB_shader_atomic_counters */
{ glGetActiveAtomicCounterBufferiv_ENUM,               "glGetActiveAtomicCounterBufferiv",               egl3_getActiveAtomicCounterBufferiv },
/* GL_ARB_shader_image_load_store */
{ glBindImageTexture_ENUM,                             "glBindImageTexture",                             egl3_bindImageTexture },
{ glMemoryBarrier_ENUM,                                "glMemoryBarrier",                                egl3_memoryBarrier },
/* GL_ARB_shading_language_packing */
/* GL_ARB_texture_storage */
{ glTexStorage1D_ENUM,                                 "glTexStorage1D",                                 egl3_texStorage1D },
{ glTexStorage2D_ENUM,                                 "glTexStorage2D",                                 egl3_texStorage2D },
{ glTexStorage3D_ENUM,                                 "glTexStorage3D",                                 egl3_texStorage3D },
{ glTextureStorage1DEXT_ENUM,                          "glTextureStorage1DEXT",                          egl3_textureStorage1DEXT },
{ glTextureStorage2DEXT_ENUM,                          "glTextureStorage2DEXT",                          egl3_textureStorage2DEXT },
{ glTextureStorage3DEXT_ENUM,                          "glTextureStorage3DEXT",                          egl3_textureStorage3DEXT },

#endif // COMPILE_GL3
