/*
 *  Copyright (c) 2012 David Koch
 *
 *  See the file "license.terms" for information on usage and redistribution
 *  of this file, and for a DISCLAIMER OF ALL WARRANTIES.
 *
 *     $Id: exdl_glcorearb_fp.h,v 1.5 2005/06/29 14:45:38 dgud Exp $
 */

/* File included in "exdl_wrapper.c" */

#ifdef COMPILE_GLCOREARB

/* GL_VERSION_1_0 */
{ glCullFace_ENUM,                                     "glCullFace",                                     eglc_cullFace },
{ glFrontFace_ENUM,                                    "glFrontFace",                                    eglc_frontFace },
{ glHint_ENUM,                                         "glHint",                                         eglc_hint },
{ glLineWidth_ENUM,                                    "glLineWidth",                                    eglc_lineWidth },
{ glPointSize_ENUM,                                    "glPointSize",                                    eglc_pointSize },
{ glPolygonMode_ENUM,                                  "glPolygonMode",                                  eglc_polygonMode },
{ glScissor_ENUM,                                      "glScissor",                                      eglc_scissor },
{ glTexParameterf_ENUM,                                "glTexParameterf",                                eglc_texParameterf },
{ glTexParameterfv_ENUM,                               "glTexParameterfv",                               eglc_texParameterfv },
{ glTexParameteri_ENUM,                                "glTexParameteri",                                eglc_texParameteri },
{ glTexParameteriv_ENUM,                               "glTexParameteriv",                               eglc_texParameteriv },
{ glTexImage1D_ENUM,                                   "glTexImage1D",                                   eglc_texImage1D },
{ glTexImage2D_ENUM,                                   "glTexImage2D",                                   eglc_texImage2D },
{ glDrawBuffer_ENUM,                                   "glDrawBuffer",                                   eglc_drawBuffer },
{ glClear_ENUM,                                        "glClear",                                        eglc_clear },
{ glClearColor_ENUM,                                   "glClearColor",                                   eglc_clearColor },
{ glClearStencil_ENUM,                                 "glClearStencil",                                 eglc_clearStencil },
{ glClearDepth_ENUM,                                   "glClearDepth",                                   eglc_clearDepth },
{ glStencilMask_ENUM,                                  "glStencilMask",                                  eglc_stencilMask },
{ glColorMask_ENUM,                                    "glColorMask",                                    eglc_colorMask },
{ glDepthMask_ENUM,                                    "glDepthMask",                                    eglc_depthMask },
{ glDisable_ENUM,                                      "glDisable",                                      eglc_disable },
{ glEnable_ENUM,                                       "glEnable",                                       eglc_enable },
{ glFinish_ENUM,                                       "glFinish",                                       eglc_finish },
{ glFlush_ENUM,                                        "glFlush",                                        eglc_flush },
{ glBlendFunc_ENUM,                                    "glBlendFunc",                                    eglc_blendFunc },
{ glLogicOp_ENUM,                                      "glLogicOp",                                      eglc_logicOp },
{ glStencilFunc_ENUM,                                  "glStencilFunc",                                  eglc_stencilFunc },
{ glStencilOp_ENUM,                                    "glStencilOp",                                    eglc_stencilOp },
{ glDepthFunc_ENUM,                                    "glDepthFunc",                                    eglc_depthFunc },
{ glPixelStoref_ENUM,                                  "glPixelStoref",                                  eglc_pixelStoref },
{ glPixelStorei_ENUM,                                  "glPixelStorei",                                  eglc_pixelStorei },
{ glReadBuffer_ENUM,                                   "glReadBuffer",                                   eglc_readBuffer },
{ glReadPixels_ENUM,                                   "glReadPixels",                                   eglc_readPixels },
{ glGetBooleanv_ENUM,                                  "glGetBooleanv",                                  eglc_getBooleanv },
{ glGetDoublev_ENUM,                                   "glGetDoublev",                                   eglc_getDoublev },
{ glGetError_ENUM,                                     "glGetError",                                     eglc_getError },
{ glGetFloatv_ENUM,                                    "glGetFloatv",                                    eglc_getFloatv },
{ glGetIntegerv_ENUM,                                  "glGetIntegerv",                                  eglc_getIntegerv },
{ glGetString_ENUM,                                    "glGetString",                                    eglc_getString },
{ glGetTexImage_ENUM,                                  "glGetTexImage",                                  eglc_getTexImage },
{ glGetTexParameterfv_ENUM,                            "glGetTexParameterfv",                            eglc_getTexParameterfv },
{ glGetTexParameteriv_ENUM,                            "glGetTexParameteriv",                            eglc_getTexParameteriv },
{ glGetTexLevelParameterfv_ENUM,                       "glGetTexLevelParameterfv",                       eglc_getTexLevelParameterfv },
{ glGetTexLevelParameteriv_ENUM,                       "glGetTexLevelParameteriv",                       eglc_getTexLevelParameteriv },
{ glIsEnabled_ENUM,                                    "glIsEnabled",                                    eglc_isEnabled },
{ glDepthRange_ENUM,                                   "glDepthRange",                                   eglc_depthRange },
{ glViewport_ENUM,                                     "glViewport",                                     eglc_viewport },
/* GL_VERSION_1_1 */
{ glDrawArrays_ENUM,                                   "glDrawArrays",                                   eglc_drawArrays },
{ glDrawElements_ENUM,                                 "glDrawElements",                                 eglc_drawElements },
{ glGetPointerv_ENUM,                                  "glGetPointerv",                                  eglc_getPointerv },
{ glPolygonOffset_ENUM,                                "glPolygonOffset",                                eglc_polygonOffset },
{ glCopyTexImage1D_ENUM,                               "glCopyTexImage1D",                               eglc_copyTexImage1D },
{ glCopyTexImage2D_ENUM,                               "glCopyTexImage2D",                               eglc_copyTexImage2D },
{ glCopyTexSubImage1D_ENUM,                            "glCopyTexSubImage1D",                            eglc_copyTexSubImage1D },
{ glCopyTexSubImage2D_ENUM,                            "glCopyTexSubImage2D",                            eglc_copyTexSubImage2D },
{ glTexSubImage1D_ENUM,                                "glTexSubImage1D",                                eglc_texSubImage1D },
{ glTexSubImage2D_ENUM,                                "glTexSubImage2D",                                eglc_texSubImage2D },
{ glBindTexture_ENUM,                                  "glBindTexture",                                  eglc_bindTexture },
{ glDeleteTextures_ENUM,                               "glDeleteTextures",                               eglc_deleteTextures },
{ glGenTextures_ENUM,                                  "glGenTextures",                                  eglc_genTextures },
{ glIsTexture_ENUM,                                    "glIsTexture",                                    eglc_isTexture },
/* GL_VERSION_1_2 */
{ glBlendColor_ENUM,                                   "glBlendColor",                                   eglc_blendColor },
{ glBlendEquation_ENUM,                                "glBlendEquation",                                eglc_blendEquation },
{ glDrawRangeElements_ENUM,                            "glDrawRangeElements",                            eglc_drawRangeElements },
{ glTexImage3D_ENUM,                                   "glTexImage3D",                                   eglc_texImage3D },
{ glTexSubImage3D_ENUM,                                "glTexSubImage3D",                                eglc_texSubImage3D },
{ glCopyTexSubImage3D_ENUM,                            "glCopyTexSubImage3D",                            eglc_copyTexSubImage3D },
/* GL_VERSION_1_3 */
{ glActiveTexture_ENUM,                                "glActiveTexture",                                eglc_activeTexture },
{ glSampleCoverage_ENUM,                               "glSampleCoverage",                               eglc_sampleCoverage },
{ glCompressedTexImage3D_ENUM,                         "glCompressedTexImage3D",                         eglc_compressedTexImage3D },
{ glCompressedTexImage2D_ENUM,                         "glCompressedTexImage2D",                         eglc_compressedTexImage2D },
{ glCompressedTexImage1D_ENUM,                         "glCompressedTexImage1D",                         eglc_compressedTexImage1D },
{ glCompressedTexSubImage3D_ENUM,                      "glCompressedTexSubImage3D",                      eglc_compressedTexSubImage3D },
{ glCompressedTexSubImage2D_ENUM,                      "glCompressedTexSubImage2D",                      eglc_compressedTexSubImage2D },
{ glCompressedTexSubImage1D_ENUM,                      "glCompressedTexSubImage1D",                      eglc_compressedTexSubImage1D },
{ glGetCompressedTexImage_ENUM,                        "glGetCompressedTexImage",                        eglc_getCompressedTexImage },
/* GL_VERSION_1_4 */
{ glBlendFuncSeparate_ENUM,                            "glBlendFuncSeparate",                            eglc_blendFuncSeparate },
{ glMultiDrawArrays_ENUM,                              "glMultiDrawArrays",                              eglc_multiDrawArrays },
{ glMultiDrawElements_ENUM,                            "glMultiDrawElements",                            eglc_multiDrawElements },
{ glPointParameterf_ENUM,                              "glPointParameterf",                              eglc_pointParameterf },
{ glPointParameterfv_ENUM,                             "glPointParameterfv",                             eglc_pointParameterfv },
{ glPointParameteri_ENUM,                              "glPointParameteri",                              eglc_pointParameteri },
{ glPointParameteriv_ENUM,                             "glPointParameteriv",                             eglc_pointParameteriv },
/* GL_VERSION_1_5 */
{ glGenQueries_ENUM,                                   "glGenQueries",                                   eglc_genQueries },
{ glDeleteQueries_ENUM,                                "glDeleteQueries",                                eglc_deleteQueries },
{ glIsQuery_ENUM,                                      "glIsQuery",                                      eglc_isQuery },
{ glBeginQuery_ENUM,                                   "glBeginQuery",                                   eglc_beginQuery },
{ glEndQuery_ENUM,                                     "glEndQuery",                                     eglc_endQuery },
{ glGetQueryiv_ENUM,                                   "glGetQueryiv",                                   eglc_getQueryiv },
{ glGetQueryObjectiv_ENUM,                             "glGetQueryObjectiv",                             eglc_getQueryObjectiv },
{ glGetQueryObjectuiv_ENUM,                            "glGetQueryObjectuiv",                            eglc_getQueryObjectuiv },
{ glBindBuffer_ENUM,                                   "glBindBuffer",                                   eglc_bindBuffer },
{ glDeleteBuffers_ENUM,                                "glDeleteBuffers",                                eglc_deleteBuffers },
{ glGenBuffers_ENUM,                                   "glGenBuffers",                                   eglc_genBuffers },
{ glIsBuffer_ENUM,                                     "glIsBuffer",                                     eglc_isBuffer },
{ glBufferData_ENUM,                                   "glBufferData",                                   eglc_bufferData },
{ glBufferSubData_ENUM,                                "glBufferSubData",                                eglc_bufferSubData },
{ glGetBufferSubData_ENUM,                             "glGetBufferSubData",                             eglc_getBufferSubData },
{ glMapBuffer_ENUM,                                    "glMapBuffer",                                    eglc_mapBuffer },
{ glUnmapBuffer_ENUM,                                  "glUnmapBuffer",                                  eglc_unmapBuffer },
{ glGetBufferParameteriv_ENUM,                         "glGetBufferParameteriv",                         eglc_getBufferParameteriv },
{ glGetBufferPointerv_ENUM,                            "glGetBufferPointerv",                            eglc_getBufferPointerv },
/* GL_VERSION_2_0 */
{ glBlendEquationSeparate_ENUM,                        "glBlendEquationSeparate",                        eglc_blendEquationSeparate },
{ glDrawBuffers_ENUM,                                  "glDrawBuffers",                                  eglc_drawBuffers },
{ glStencilOpSeparate_ENUM,                            "glStencilOpSeparate",                            eglc_stencilOpSeparate },
{ glStencilFuncSeparate_ENUM,                          "glStencilFuncSeparate",                          eglc_stencilFuncSeparate },
{ glStencilMaskSeparate_ENUM,                          "glStencilMaskSeparate",                          eglc_stencilMaskSeparate },
{ glAttachShader_ENUM,                                 "glAttachShader",                                 eglc_attachShader },
{ glBindAttribLocation_ENUM,                           "glBindAttribLocation",                           eglc_bindAttribLocation },
{ glCompileShader_ENUM,                                "glCompileShader",                                eglc_compileShader },
{ glCreateProgram_ENUM,                                "glCreateProgram",                                eglc_createProgram },
{ glCreateShader_ENUM,                                 "glCreateShader",                                 eglc_createShader },
{ glDeleteProgram_ENUM,                                "glDeleteProgram",                                eglc_deleteProgram },
{ glDeleteShader_ENUM,                                 "glDeleteShader",                                 eglc_deleteShader },
{ glDetachShader_ENUM,                                 "glDetachShader",                                 eglc_detachShader },
{ glDisableVertexAttribArray_ENUM,                     "glDisableVertexAttribArray",                     eglc_disableVertexAttribArray },
{ glEnableVertexAttribArray_ENUM,                      "glEnableVertexAttribArray",                      eglc_enableVertexAttribArray },
{ glGetActiveAttrib_ENUM,                              "glGetActiveAttrib",                              eglc_getActiveAttrib },
{ glGetActiveUniform_ENUM,                             "glGetActiveUniform",                             eglc_getActiveUniform },
{ glGetAttachedShaders_ENUM,                           "glGetAttachedShaders",                           eglc_getAttachedShaders },
{ glGetAttribLocation_ENUM,                            "glGetAttribLocation",                            eglc_getAttribLocation },
{ glGetProgramiv_ENUM,                                 "glGetProgramiv",                                 eglc_getProgramiv },
{ glGetProgramInfoLog_ENUM,                            "glGetProgramInfoLog",                            eglc_getProgramInfoLog },
{ glGetShaderiv_ENUM,                                  "glGetShaderiv",                                  eglc_getShaderiv },
{ glGetShaderInfoLog_ENUM,                             "glGetShaderInfoLog",                             eglc_getShaderInfoLog },
{ glGetShaderSource_ENUM,                              "glGetShaderSource",                              eglc_getShaderSource },
{ glGetUniformLocation_ENUM,                           "glGetUniformLocation",                           eglc_getUniformLocation },
{ glGetUniformfv_ENUM,                                 "glGetUniformfv",                                 eglc_getUniformfv },
{ glGetUniformiv_ENUM,                                 "glGetUniformiv",                                 eglc_getUniformiv },
{ glGetVertexAttribdv_ENUM,                            "glGetVertexAttribdv",                            eglc_getVertexAttribdv },
{ glGetVertexAttribfv_ENUM,                            "glGetVertexAttribfv",                            eglc_getVertexAttribfv },
{ glGetVertexAttribiv_ENUM,                            "glGetVertexAttribiv",                            eglc_getVertexAttribiv },
{ glGetVertexAttribPointerv_ENUM,                      "glGetVertexAttribPointerv",                      eglc_getVertexAttribPointerv },
{ glIsProgram_ENUM,                                    "glIsProgram",                                    eglc_isProgram },
{ glIsShader_ENUM,                                     "glIsShader",                                     eglc_isShader },
{ glLinkProgram_ENUM,                                  "glLinkProgram",                                  eglc_linkProgram },
{ glShaderSource_ENUM,                                 "glShaderSource",                                 eglc_shaderSource },
{ glUseProgram_ENUM,                                   "glUseProgram",                                   eglc_useProgram },
{ glUniform1f_ENUM,                                    "glUniform1f",                                    eglc_uniform1f },
{ glUniform2f_ENUM,                                    "glUniform2f",                                    eglc_uniform2f },
{ glUniform3f_ENUM,                                    "glUniform3f",                                    eglc_uniform3f },
{ glUniform4f_ENUM,                                    "glUniform4f",                                    eglc_uniform4f },
{ glUniform1i_ENUM,                                    "glUniform1i",                                    eglc_uniform1i },
{ glUniform2i_ENUM,                                    "glUniform2i",                                    eglc_uniform2i },
{ glUniform3i_ENUM,                                    "glUniform3i",                                    eglc_uniform3i },
{ glUniform4i_ENUM,                                    "glUniform4i",                                    eglc_uniform4i },
{ glUniform1fv_ENUM,                                   "glUniform1fv",                                   eglc_uniform1fv },
{ glUniform2fv_ENUM,                                   "glUniform2fv",                                   eglc_uniform2fv },
{ glUniform3fv_ENUM,                                   "glUniform3fv",                                   eglc_uniform3fv },
{ glUniform4fv_ENUM,                                   "glUniform4fv",                                   eglc_uniform4fv },
{ glUniform1iv_ENUM,                                   "glUniform1iv",                                   eglc_uniform1iv },
{ glUniform2iv_ENUM,                                   "glUniform2iv",                                   eglc_uniform2iv },
{ glUniform3iv_ENUM,                                   "glUniform3iv",                                   eglc_uniform3iv },
{ glUniform4iv_ENUM,                                   "glUniform4iv",                                   eglc_uniform4iv },
{ glUniformMatrix2fv_ENUM,                             "glUniformMatrix2fv",                             eglc_uniformMatrix2fv },
{ glUniformMatrix3fv_ENUM,                             "glUniformMatrix3fv",                             eglc_uniformMatrix3fv },
{ glUniformMatrix4fv_ENUM,                             "glUniformMatrix4fv",                             eglc_uniformMatrix4fv },
{ glValidateProgram_ENUM,                              "glValidateProgram",                              eglc_validateProgram },
{ glVertexAttrib1d_ENUM,                               "glVertexAttrib1d",                               eglc_vertexAttrib1d },
{ glVertexAttrib1dv_ENUM,                              "glVertexAttrib1dv",                              eglc_vertexAttrib1dv },
{ glVertexAttrib1f_ENUM,                               "glVertexAttrib1f",                               eglc_vertexAttrib1f },
{ glVertexAttrib1fv_ENUM,                              "glVertexAttrib1fv",                              eglc_vertexAttrib1fv },
{ glVertexAttrib1s_ENUM,                               "glVertexAttrib1s",                               eglc_vertexAttrib1s },
{ glVertexAttrib1sv_ENUM,                              "glVertexAttrib1sv",                              eglc_vertexAttrib1sv },
{ glVertexAttrib2d_ENUM,                               "glVertexAttrib2d",                               eglc_vertexAttrib2d },
{ glVertexAttrib2dv_ENUM,                              "glVertexAttrib2dv",                              eglc_vertexAttrib2dv },
{ glVertexAttrib2f_ENUM,                               "glVertexAttrib2f",                               eglc_vertexAttrib2f },
{ glVertexAttrib2fv_ENUM,                              "glVertexAttrib2fv",                              eglc_vertexAttrib2fv },
{ glVertexAttrib2s_ENUM,                               "glVertexAttrib2s",                               eglc_vertexAttrib2s },
{ glVertexAttrib2sv_ENUM,                              "glVertexAttrib2sv",                              eglc_vertexAttrib2sv },
{ glVertexAttrib3d_ENUM,                               "glVertexAttrib3d",                               eglc_vertexAttrib3d },
{ glVertexAttrib3dv_ENUM,                              "glVertexAttrib3dv",                              eglc_vertexAttrib3dv },
{ glVertexAttrib3f_ENUM,                               "glVertexAttrib3f",                               eglc_vertexAttrib3f },
{ glVertexAttrib3fv_ENUM,                              "glVertexAttrib3fv",                              eglc_vertexAttrib3fv },
{ glVertexAttrib3s_ENUM,                               "glVertexAttrib3s",                               eglc_vertexAttrib3s },
{ glVertexAttrib3sv_ENUM,                              "glVertexAttrib3sv",                              eglc_vertexAttrib3sv },
{ glVertexAttrib4Nbv_ENUM,                             "glVertexAttrib4Nbv",                             eglc_vertexAttrib4Nbv },
{ glVertexAttrib4Niv_ENUM,                             "glVertexAttrib4Niv",                             eglc_vertexAttrib4Niv },
{ glVertexAttrib4Nsv_ENUM,                             "glVertexAttrib4Nsv",                             eglc_vertexAttrib4Nsv },
{ glVertexAttrib4Nub_ENUM,                             "glVertexAttrib4Nub",                             eglc_vertexAttrib4Nub },
{ glVertexAttrib4Nubv_ENUM,                            "glVertexAttrib4Nubv",                            eglc_vertexAttrib4Nubv },
{ glVertexAttrib4Nuiv_ENUM,                            "glVertexAttrib4Nuiv",                            eglc_vertexAttrib4Nuiv },
{ glVertexAttrib4Nusv_ENUM,                            "glVertexAttrib4Nusv",                            eglc_vertexAttrib4Nusv },
{ glVertexAttrib4bv_ENUM,                              "glVertexAttrib4bv",                              eglc_vertexAttrib4bv },
{ glVertexAttrib4d_ENUM,                               "glVertexAttrib4d",                               eglc_vertexAttrib4d },
{ glVertexAttrib4dv_ENUM,                              "glVertexAttrib4dv",                              eglc_vertexAttrib4dv },
{ glVertexAttrib4f_ENUM,                               "glVertexAttrib4f",                               eglc_vertexAttrib4f },
{ glVertexAttrib4fv_ENUM,                              "glVertexAttrib4fv",                              eglc_vertexAttrib4fv },
{ glVertexAttrib4iv_ENUM,                              "glVertexAttrib4iv",                              eglc_vertexAttrib4iv },
{ glVertexAttrib4s_ENUM,                               "glVertexAttrib4s",                               eglc_vertexAttrib4s },
{ glVertexAttrib4sv_ENUM,                              "glVertexAttrib4sv",                              eglc_vertexAttrib4sv },
{ glVertexAttrib4ubv_ENUM,                             "glVertexAttrib4ubv",                             eglc_vertexAttrib4ubv },
{ glVertexAttrib4uiv_ENUM,                             "glVertexAttrib4uiv",                             eglc_vertexAttrib4uiv },
{ glVertexAttrib4usv_ENUM,                             "glVertexAttrib4usv",                             eglc_vertexAttrib4usv },
{ glVertexAttribPointer_ENUM,                          "glVertexAttribPointer",                          eglc_vertexAttribPointer },
/* GL_VERSION_2_1 */
{ glUniformMatrix2x3fv_ENUM,                           "glUniformMatrix2x3fv",                           eglc_uniformMatrix2x3fv },
{ glUniformMatrix3x2fv_ENUM,                           "glUniformMatrix3x2fv",                           eglc_uniformMatrix3x2fv },
{ glUniformMatrix2x4fv_ENUM,                           "glUniformMatrix2x4fv",                           eglc_uniformMatrix2x4fv },
{ glUniformMatrix4x2fv_ENUM,                           "glUniformMatrix4x2fv",                           eglc_uniformMatrix4x2fv },
{ glUniformMatrix3x4fv_ENUM,                           "glUniformMatrix3x4fv",                           eglc_uniformMatrix3x4fv },
{ glUniformMatrix4x3fv_ENUM,                           "glUniformMatrix4x3fv",                           eglc_uniformMatrix4x3fv },
/* GL_VERSION_3_0 */
{ glColorMaski_ENUM,                                   "glColorMaski",                                   eglc_colorMaski },
{ glGetBooleani_v_ENUM,                                "glGetBooleani_v",                                eglc_getBooleani_v },
{ glGetIntegeri_v_ENUM,                                "glGetIntegeri_v",                                eglc_getIntegeri_v },
{ glEnablei_ENUM,                                      "glEnablei",                                      eglc_enablei },
{ glDisablei_ENUM,                                     "glDisablei",                                     eglc_disablei },
{ glIsEnabledi_ENUM,                                   "glIsEnabledi",                                   eglc_isEnabledi },
{ glBeginTransformFeedback_ENUM,                       "glBeginTransformFeedback",                       eglc_beginTransformFeedback },
{ glEndTransformFeedback_ENUM,                         "glEndTransformFeedback",                         eglc_endTransformFeedback },
{ glBindBufferRange_ENUM,                              "glBindBufferRange",                              eglc_bindBufferRange },
{ glBindBufferBase_ENUM,                               "glBindBufferBase",                               eglc_bindBufferBase },
{ glTransformFeedbackVaryings_ENUM,                    "glTransformFeedbackVaryings",                    eglc_transformFeedbackVaryings },
{ glGetTransformFeedbackVarying_ENUM,                  "glGetTransformFeedbackVarying",                  eglc_getTransformFeedbackVarying },
{ glClampColor_ENUM,                                   "glClampColor",                                   eglc_clampColor },
{ glBeginConditionalRender_ENUM,                       "glBeginConditionalRender",                       eglc_beginConditionalRender },
{ glEndConditionalRender_ENUM,                         "glEndConditionalRender",                         eglc_endConditionalRender },
{ glVertexAttribIPointer_ENUM,                         "glVertexAttribIPointer",                         eglc_vertexAttribIPointer },
{ glGetVertexAttribIiv_ENUM,                           "glGetVertexAttribIiv",                           eglc_getVertexAttribIiv },
{ glGetVertexAttribIuiv_ENUM,                          "glGetVertexAttribIuiv",                          eglc_getVertexAttribIuiv },
{ glVertexAttribI1i_ENUM,                              "glVertexAttribI1i",                              eglc_vertexAttribI1i },
{ glVertexAttribI2i_ENUM,                              "glVertexAttribI2i",                              eglc_vertexAttribI2i },
{ glVertexAttribI3i_ENUM,                              "glVertexAttribI3i",                              eglc_vertexAttribI3i },
{ glVertexAttribI4i_ENUM,                              "glVertexAttribI4i",                              eglc_vertexAttribI4i },
{ glVertexAttribI1ui_ENUM,                             "glVertexAttribI1ui",                             eglc_vertexAttribI1ui },
{ glVertexAttribI2ui_ENUM,                             "glVertexAttribI2ui",                             eglc_vertexAttribI2ui },
{ glVertexAttribI3ui_ENUM,                             "glVertexAttribI3ui",                             eglc_vertexAttribI3ui },
{ glVertexAttribI4ui_ENUM,                             "glVertexAttribI4ui",                             eglc_vertexAttribI4ui },
{ glVertexAttribI1iv_ENUM,                             "glVertexAttribI1iv",                             eglc_vertexAttribI1iv },
{ glVertexAttribI2iv_ENUM,                             "glVertexAttribI2iv",                             eglc_vertexAttribI2iv },
{ glVertexAttribI3iv_ENUM,                             "glVertexAttribI3iv",                             eglc_vertexAttribI3iv },
{ glVertexAttribI4iv_ENUM,                             "glVertexAttribI4iv",                             eglc_vertexAttribI4iv },
{ glVertexAttribI1uiv_ENUM,                            "glVertexAttribI1uiv",                            eglc_vertexAttribI1uiv },
{ glVertexAttribI2uiv_ENUM,                            "glVertexAttribI2uiv",                            eglc_vertexAttribI2uiv },
{ glVertexAttribI3uiv_ENUM,                            "glVertexAttribI3uiv",                            eglc_vertexAttribI3uiv },
{ glVertexAttribI4uiv_ENUM,                            "glVertexAttribI4uiv",                            eglc_vertexAttribI4uiv },
{ glVertexAttribI4bv_ENUM,                             "glVertexAttribI4bv",                             eglc_vertexAttribI4bv },
{ glVertexAttribI4sv_ENUM,                             "glVertexAttribI4sv",                             eglc_vertexAttribI4sv },
{ glVertexAttribI4ubv_ENUM,                            "glVertexAttribI4ubv",                            eglc_vertexAttribI4ubv },
{ glVertexAttribI4usv_ENUM,                            "glVertexAttribI4usv",                            eglc_vertexAttribI4usv },
{ glGetUniformuiv_ENUM,                                "glGetUniformuiv",                                eglc_getUniformuiv },
{ glBindFragDataLocation_ENUM,                         "glBindFragDataLocation",                         eglc_bindFragDataLocation },
{ glGetFragDataLocation_ENUM,                          "glGetFragDataLocation",                          eglc_getFragDataLocation },
{ glUniform1ui_ENUM,                                   "glUniform1ui",                                   eglc_uniform1ui },
{ glUniform2ui_ENUM,                                   "glUniform2ui",                                   eglc_uniform2ui },
{ glUniform3ui_ENUM,                                   "glUniform3ui",                                   eglc_uniform3ui },
{ glUniform4ui_ENUM,                                   "glUniform4ui",                                   eglc_uniform4ui },
{ glUniform1uiv_ENUM,                                  "glUniform1uiv",                                  eglc_uniform1uiv },
{ glUniform2uiv_ENUM,                                  "glUniform2uiv",                                  eglc_uniform2uiv },
{ glUniform3uiv_ENUM,                                  "glUniform3uiv",                                  eglc_uniform3uiv },
{ glUniform4uiv_ENUM,                                  "glUniform4uiv",                                  eglc_uniform4uiv },
{ glTexParameterIiv_ENUM,                              "glTexParameterIiv",                              eglc_texParameterIiv },
{ glTexParameterIuiv_ENUM,                             "glTexParameterIuiv",                             eglc_texParameterIuiv },
{ glGetTexParameterIiv_ENUM,                           "glGetTexParameterIiv",                           eglc_getTexParameterIiv },
{ glGetTexParameterIuiv_ENUM,                          "glGetTexParameterIuiv",                          eglc_getTexParameterIuiv },
{ glClearBufferiv_ENUM,                                "glClearBufferiv",                                eglc_clearBufferiv },
{ glClearBufferuiv_ENUM,                               "glClearBufferuiv",                               eglc_clearBufferuiv },
{ glClearBufferfv_ENUM,                                "glClearBufferfv",                                eglc_clearBufferfv },
{ glClearBufferfi_ENUM,                                "glClearBufferfi",                                eglc_clearBufferfi },
{ glGetStringi_ENUM,                                   "glGetStringi",                                   eglc_getStringi },
/* GL_VERSION_3_1 */
{ glDrawArraysInstanced_ENUM,                          "glDrawArraysInstanced",                          eglc_drawArraysInstanced },
{ glDrawElementsInstanced_ENUM,                        "glDrawElementsInstanced",                        eglc_drawElementsInstanced },
{ glTexBuffer_ENUM,                                    "glTexBuffer",                                    eglc_texBuffer },
{ glPrimitiveRestartIndex_ENUM,                        "glPrimitiveRestartIndex",                        eglc_primitiveRestartIndex },
/* GL_VERSION_3_2 */
{ glGetInteger64i_v_ENUM,                              "glGetInteger64i_v",                              eglc_getInteger64i_v },
{ glGetBufferParameteri64v_ENUM,                       "glGetBufferParameteri64v",                       eglc_getBufferParameteri64v },
{ glFramebufferTexture_ENUM,                           "glFramebufferTexture",                           eglc_framebufferTexture },
/* GL_VERSION_3_3 */
{ glVertexAttribDivisor_ENUM,                          "glVertexAttribDivisor",                          eglc_vertexAttribDivisor },
/* GL_VERSION_4_0 */
{ glMinSampleShading_ENUM,                             "glMinSampleShading",                             eglc_minSampleShading },
{ glBlendEquationi_ENUM,                               "glBlendEquationi",                               eglc_blendEquationi },
{ glBlendEquationSeparatei_ENUM,                       "glBlendEquationSeparatei",                       eglc_blendEquationSeparatei },
{ glBlendFunci_ENUM,                                   "glBlendFunci",                                   eglc_blendFunci },
{ glBlendFuncSeparatei_ENUM,                           "glBlendFuncSeparatei",                           eglc_blendFuncSeparatei },
/* GL_VERSION_4_1 */
/* GL_VERSION_4_2 */
/* GL_VERSION_4_3 */
/* GL_ARB_depth_buffer_float */
/* GL_ARB_framebuffer_object */
{ glIsRenderbuffer_ENUM,                               "glIsRenderbuffer",                               eglc_isRenderbuffer },
{ glBindRenderbuffer_ENUM,                             "glBindRenderbuffer",                             eglc_bindRenderbuffer },
{ glDeleteRenderbuffers_ENUM,                          "glDeleteRenderbuffers",                          eglc_deleteRenderbuffers },
{ glGenRenderbuffers_ENUM,                             "glGenRenderbuffers",                             eglc_genRenderbuffers },
{ glRenderbufferStorage_ENUM,                          "glRenderbufferStorage",                          eglc_renderbufferStorage },
{ glGetRenderbufferParameteriv_ENUM,                   "glGetRenderbufferParameteriv",                   eglc_getRenderbufferParameteriv },
{ glIsFramebuffer_ENUM,                                "glIsFramebuffer",                                eglc_isFramebuffer },
{ glBindFramebuffer_ENUM,                              "glBindFramebuffer",                              eglc_bindFramebuffer },
{ glDeleteFramebuffers_ENUM,                           "glDeleteFramebuffers",                           eglc_deleteFramebuffers },
{ glGenFramebuffers_ENUM,                              "glGenFramebuffers",                              eglc_genFramebuffers },
{ glCheckFramebufferStatus_ENUM,                       "glCheckFramebufferStatus",                       eglc_checkFramebufferStatus },
{ glFramebufferTexture1D_ENUM,                         "glFramebufferTexture1D",                         eglc_framebufferTexture1D },
{ glFramebufferTexture2D_ENUM,                         "glFramebufferTexture2D",                         eglc_framebufferTexture2D },
{ glFramebufferTexture3D_ENUM,                         "glFramebufferTexture3D",                         eglc_framebufferTexture3D },
{ glFramebufferRenderbuffer_ENUM,                      "glFramebufferRenderbuffer",                      eglc_framebufferRenderbuffer },
{ glGetFramebufferAttachmentParameteriv_ENUM,          "glGetFramebufferAttachmentParameteriv",          eglc_getFramebufferAttachmentParameteriv },
{ glGenerateMipmap_ENUM,                               "glGenerateMipmap",                               eglc_generateMipmap },
{ glBlitFramebuffer_ENUM,                              "glBlitFramebuffer",                              eglc_blitFramebuffer },
{ glRenderbufferStorageMultisample_ENUM,               "glRenderbufferStorageMultisample",               eglc_renderbufferStorageMultisample },
{ glFramebufferTextureLayer_ENUM,                      "glFramebufferTextureLayer",                      eglc_framebufferTextureLayer },
/* GL_ARB_map_buffer_range */
{ glMapBufferRange_ENUM,                               "glMapBufferRange",                               eglc_mapBufferRange },
{ glFlushMappedBufferRange_ENUM,                       "glFlushMappedBufferRange",                       eglc_flushMappedBufferRange },
/* GL_ARB_vertex_array_object */
{ glBindVertexArray_ENUM,                              "glBindVertexArray",                              eglc_bindVertexArray },
{ glDeleteVertexArrays_ENUM,                           "glDeleteVertexArrays",                           eglc_deleteVertexArrays },
{ glGenVertexArrays_ENUM,                              "glGenVertexArrays",                              eglc_genVertexArrays },
{ glIsVertexArray_ENUM,                                "glIsVertexArray",                                eglc_isVertexArray },
/* GL_ARB_uniform_buffer_object */
{ glGetUniformIndices_ENUM,                            "glGetUniformIndices",                            eglc_getUniformIndices },
{ glGetActiveUniformsiv_ENUM,                          "glGetActiveUniformsiv",                          eglc_getActiveUniformsiv },
{ glGetActiveUniformName_ENUM,                         "glGetActiveUniformName",                         eglc_getActiveUniformName },
{ glGetUniformBlockIndex_ENUM,                         "glGetUniformBlockIndex",                         eglc_getUniformBlockIndex },
{ glGetActiveUniformBlockiv_ENUM,                      "glGetActiveUniformBlockiv",                      eglc_getActiveUniformBlockiv },
{ glGetActiveUniformBlockName_ENUM,                    "glGetActiveUniformBlockName",                    eglc_getActiveUniformBlockName },
{ glUniformBlockBinding_ENUM,                          "glUniformBlockBinding",                          eglc_uniformBlockBinding },
/* GL_ARB_copy_buffer */
{ glCopyBufferSubData_ENUM,                            "glCopyBufferSubData",                            eglc_copyBufferSubData },
/* GL_ARB_draw_elements_base_vertex */
{ glDrawElementsBaseVertex_ENUM,                       "glDrawElementsBaseVertex",                       eglc_drawElementsBaseVertex },
{ glDrawRangeElementsBaseVertex_ENUM,                  "glDrawRangeElementsBaseVertex",                  eglc_drawRangeElementsBaseVertex },
{ glDrawElementsInstancedBaseVertex_ENUM,              "glDrawElementsInstancedBaseVertex",              eglc_drawElementsInstancedBaseVertex },
{ glMultiDrawElementsBaseVertex_ENUM,                  "glMultiDrawElementsBaseVertex",                  eglc_multiDrawElementsBaseVertex },
/* GL_ARB_provoking_vertex */
{ glProvokingVertex_ENUM,                              "glProvokingVertex",                              eglc_provokingVertex },
/* GL_ARB_sync */
{ glFenceSync_ENUM,                                    "glFenceSync",                                    eglc_fenceSync },
{ glIsSync_ENUM,                                       "glIsSync",                                       eglc_isSync },
{ glDeleteSync_ENUM,                                   "glDeleteSync",                                   eglc_deleteSync },
{ glClientWaitSync_ENUM,                               "glClientWaitSync",                               eglc_clientWaitSync },
{ glWaitSync_ENUM,                                     "glWaitSync",                                     eglc_waitSync },
{ glGetInteger64v_ENUM,                                "glGetInteger64v",                                eglc_getInteger64v },
{ glGetSynciv_ENUM,                                    "glGetSynciv",                                    eglc_getSynciv },
/* GL_ARB_texture_multisample */
{ glTexImage2DMultisample_ENUM,                        "glTexImage2DMultisample",                        eglc_texImage2DMultisample },
{ glTexImage3DMultisample_ENUM,                        "glTexImage3DMultisample",                        eglc_texImage3DMultisample },
{ glGetMultisamplefv_ENUM,                             "glGetMultisamplefv",                             eglc_getMultisamplefv },
{ glSampleMaski_ENUM,                                  "glSampleMaski",                                  eglc_sampleMaski },
/* GL_ARB_draw_buffers_blend */
{ glBlendEquationiARB_ENUM,                            "glBlendEquationiARB",                            eglc_blendEquationiARB },
{ glBlendEquationSeparateiARB_ENUM,                    "glBlendEquationSeparateiARB",                    eglc_blendEquationSeparateiARB },
{ glBlendFunciARB_ENUM,                                "glBlendFunciARB",                                eglc_blendFunciARB },
{ glBlendFuncSeparateiARB_ENUM,                        "glBlendFuncSeparateiARB",                        eglc_blendFuncSeparateiARB },
/* GL_ARB_sample_shading */
{ glMinSampleShadingARB_ENUM,                          "glMinSampleShadingARB",                          eglc_minSampleShadingARB },
/* GL_ARB_texture_cube_map_array */
/* GL_ARB_texture_gather */
/* GL_ARB_texture_query_lod */
/* GL_ARB_shading_language_include */
{ glNamedStringARB_ENUM,                               "glNamedStringARB",                               eglc_namedStringARB },
{ glDeleteNamedStringARB_ENUM,                         "glDeleteNamedStringARB",                         eglc_deleteNamedStringARB },
{ glCompileShaderIncludeARB_ENUM,                      "glCompileShaderIncludeARB",                      eglc_compileShaderIncludeARB },
{ glIsNamedStringARB_ENUM,                             "glIsNamedStringARB",                             eglc_isNamedStringARB },
{ glGetNamedStringARB_ENUM,                            "glGetNamedStringARB",                            eglc_getNamedStringARB },
{ glGetNamedStringivARB_ENUM,                          "glGetNamedStringivARB",                          eglc_getNamedStringivARB },
/* GL_ARB_texture_compression_bptc */
/* GL_ARB_blend_func_extended */
{ glBindFragDataLocationIndexed_ENUM,                  "glBindFragDataLocationIndexed",                  eglc_bindFragDataLocationIndexed },
{ glGetFragDataIndex_ENUM,                             "glGetFragDataIndex",                             eglc_getFragDataIndex },
/* GL_ARB_explicit_attrib_location */
/* GL_ARB_occlusion_query2 */
/* GL_ARB_sampler_objects */
{ glGenSamplers_ENUM,                                  "glGenSamplers",                                  eglc_genSamplers },
{ glDeleteSamplers_ENUM,                               "glDeleteSamplers",                               eglc_deleteSamplers },
{ glIsSampler_ENUM,                                    "glIsSampler",                                    eglc_isSampler },
{ glBindSampler_ENUM,                                  "glBindSampler",                                  eglc_bindSampler },
{ glSamplerParameteri_ENUM,                            "glSamplerParameteri",                            eglc_samplerParameteri },
{ glSamplerParameteriv_ENUM,                           "glSamplerParameteriv",                           eglc_samplerParameteriv },
{ glSamplerParameterf_ENUM,                            "glSamplerParameterf",                            eglc_samplerParameterf },
{ glSamplerParameterfv_ENUM,                           "glSamplerParameterfv",                           eglc_samplerParameterfv },
{ glSamplerParameterIiv_ENUM,                          "glSamplerParameterIiv",                          eglc_samplerParameterIiv },
{ glSamplerParameterIuiv_ENUM,                         "glSamplerParameterIuiv",                         eglc_samplerParameterIuiv },
{ glGetSamplerParameteriv_ENUM,                        "glGetSamplerParameteriv",                        eglc_getSamplerParameteriv },
{ glGetSamplerParameterIiv_ENUM,                       "glGetSamplerParameterIiv",                       eglc_getSamplerParameterIiv },
{ glGetSamplerParameterfv_ENUM,                        "glGetSamplerParameterfv",                        eglc_getSamplerParameterfv },
{ glGetSamplerParameterIuiv_ENUM,                      "glGetSamplerParameterIuiv",                      eglc_getSamplerParameterIuiv },
/* GL_ARB_texture_rgb10_a2ui */
/* GL_ARB_texture_swizzle */
/* GL_ARB_timer_query */
{ glQueryCounter_ENUM,                                 "glQueryCounter",                                 eglc_queryCounter },
{ glGetQueryObjecti64v_ENUM,                           "glGetQueryObjecti64v",                           eglc_getQueryObjecti64v },
{ glGetQueryObjectui64v_ENUM,                          "glGetQueryObjectui64v",                          eglc_getQueryObjectui64v },
/* GL_ARB_vertex_type_2_10_10_10_rev */
{ glVertexP2ui_ENUM,                                   "glVertexP2ui",                                   eglc_vertexP2ui },
{ glVertexP2uiv_ENUM,                                  "glVertexP2uiv",                                  eglc_vertexP2uiv },
{ glVertexP3ui_ENUM,                                   "glVertexP3ui",                                   eglc_vertexP3ui },
{ glVertexP3uiv_ENUM,                                  "glVertexP3uiv",                                  eglc_vertexP3uiv },
{ glVertexP4ui_ENUM,                                   "glVertexP4ui",                                   eglc_vertexP4ui },
{ glVertexP4uiv_ENUM,                                  "glVertexP4uiv",                                  eglc_vertexP4uiv },
{ glTexCoordP1ui_ENUM,                                 "glTexCoordP1ui",                                 eglc_texCoordP1ui },
{ glTexCoordP1uiv_ENUM,                                "glTexCoordP1uiv",                                eglc_texCoordP1uiv },
{ glTexCoordP2ui_ENUM,                                 "glTexCoordP2ui",                                 eglc_texCoordP2ui },
{ glTexCoordP2uiv_ENUM,                                "glTexCoordP2uiv",                                eglc_texCoordP2uiv },
{ glTexCoordP3ui_ENUM,                                 "glTexCoordP3ui",                                 eglc_texCoordP3ui },
{ glTexCoordP3uiv_ENUM,                                "glTexCoordP3uiv",                                eglc_texCoordP3uiv },
{ glTexCoordP4ui_ENUM,                                 "glTexCoordP4ui",                                 eglc_texCoordP4ui },
{ glTexCoordP4uiv_ENUM,                                "glTexCoordP4uiv",                                eglc_texCoordP4uiv },
{ glMultiTexCoordP1ui_ENUM,                            "glMultiTexCoordP1ui",                            eglc_multiTexCoordP1ui },
{ glMultiTexCoordP1uiv_ENUM,                           "glMultiTexCoordP1uiv",                           eglc_multiTexCoordP1uiv },
{ glMultiTexCoordP2ui_ENUM,                            "glMultiTexCoordP2ui",                            eglc_multiTexCoordP2ui },
{ glMultiTexCoordP2uiv_ENUM,                           "glMultiTexCoordP2uiv",                           eglc_multiTexCoordP2uiv },
{ glMultiTexCoordP3ui_ENUM,                            "glMultiTexCoordP3ui",                            eglc_multiTexCoordP3ui },
{ glMultiTexCoordP3uiv_ENUM,                           "glMultiTexCoordP3uiv",                           eglc_multiTexCoordP3uiv },
{ glMultiTexCoordP4ui_ENUM,                            "glMultiTexCoordP4ui",                            eglc_multiTexCoordP4ui },
{ glMultiTexCoordP4uiv_ENUM,                           "glMultiTexCoordP4uiv",                           eglc_multiTexCoordP4uiv },
{ glNormalP3ui_ENUM,                                   "glNormalP3ui",                                   eglc_normalP3ui },
{ glNormalP3uiv_ENUM,                                  "glNormalP3uiv",                                  eglc_normalP3uiv },
{ glColorP3ui_ENUM,                                    "glColorP3ui",                                    eglc_colorP3ui },
{ glColorP3uiv_ENUM,                                   "glColorP3uiv",                                   eglc_colorP3uiv },
{ glColorP4ui_ENUM,                                    "glColorP4ui",                                    eglc_colorP4ui },
{ glColorP4uiv_ENUM,                                   "glColorP4uiv",                                   eglc_colorP4uiv },
{ glSecondaryColorP3ui_ENUM,                           "glSecondaryColorP3ui",                           eglc_secondaryColorP3ui },
{ glSecondaryColorP3uiv_ENUM,                          "glSecondaryColorP3uiv",                          eglc_secondaryColorP3uiv },
{ glVertexAttribP1ui_ENUM,                             "glVertexAttribP1ui",                             eglc_vertexAttribP1ui },
{ glVertexAttribP1uiv_ENUM,                            "glVertexAttribP1uiv",                            eglc_vertexAttribP1uiv },
{ glVertexAttribP2ui_ENUM,                             "glVertexAttribP2ui",                             eglc_vertexAttribP2ui },
{ glVertexAttribP2uiv_ENUM,                            "glVertexAttribP2uiv",                            eglc_vertexAttribP2uiv },
{ glVertexAttribP3ui_ENUM,                             "glVertexAttribP3ui",                             eglc_vertexAttribP3ui },
{ glVertexAttribP3uiv_ENUM,                            "glVertexAttribP3uiv",                            eglc_vertexAttribP3uiv },
{ glVertexAttribP4ui_ENUM,                             "glVertexAttribP4ui",                             eglc_vertexAttribP4ui },
{ glVertexAttribP4uiv_ENUM,                            "glVertexAttribP4uiv",                            eglc_vertexAttribP4uiv },
/* GL_ARB_draw_indirect */
{ glDrawArraysIndirect_ENUM,                           "glDrawArraysIndirect",                           eglc_drawArraysIndirect },
{ glDrawElementsIndirect_ENUM,                         "glDrawElementsIndirect",                         eglc_drawElementsIndirect },
/* GL_ARB_gpu_shader5 */
/* GL_ARB_gpu_shader_fp64 */
{ glUniform1d_ENUM,                                    "glUniform1d",                                    eglc_uniform1d },
{ glUniform2d_ENUM,                                    "glUniform2d",                                    eglc_uniform2d },
{ glUniform3d_ENUM,                                    "glUniform3d",                                    eglc_uniform3d },
{ glUniform4d_ENUM,                                    "glUniform4d",                                    eglc_uniform4d },
{ glUniform1dv_ENUM,                                   "glUniform1dv",                                   eglc_uniform1dv },
{ glUniform2dv_ENUM,                                   "glUniform2dv",                                   eglc_uniform2dv },
{ glUniform3dv_ENUM,                                   "glUniform3dv",                                   eglc_uniform3dv },
{ glUniform4dv_ENUM,                                   "glUniform4dv",                                   eglc_uniform4dv },
{ glUniformMatrix2dv_ENUM,                             "glUniformMatrix2dv",                             eglc_uniformMatrix2dv },
{ glUniformMatrix3dv_ENUM,                             "glUniformMatrix3dv",                             eglc_uniformMatrix3dv },
{ glUniformMatrix4dv_ENUM,                             "glUniformMatrix4dv",                             eglc_uniformMatrix4dv },
{ glUniformMatrix2x3dv_ENUM,                           "glUniformMatrix2x3dv",                           eglc_uniformMatrix2x3dv },
{ glUniformMatrix2x4dv_ENUM,                           "glUniformMatrix2x4dv",                           eglc_uniformMatrix2x4dv },
{ glUniformMatrix3x2dv_ENUM,                           "glUniformMatrix3x2dv",                           eglc_uniformMatrix3x2dv },
{ glUniformMatrix3x4dv_ENUM,                           "glUniformMatrix3x4dv",                           eglc_uniformMatrix3x4dv },
{ glUniformMatrix4x2dv_ENUM,                           "glUniformMatrix4x2dv",                           eglc_uniformMatrix4x2dv },
{ glUniformMatrix4x3dv_ENUM,                           "glUniformMatrix4x3dv",                           eglc_uniformMatrix4x3dv },
{ glGetUniformdv_ENUM,                                 "glGetUniformdv",                                 eglc_getUniformdv },
/* GL_ARB_shader_subroutine */
{ glGetSubroutineUniformLocation_ENUM,                 "glGetSubroutineUniformLocation",                 eglc_getSubroutineUniformLocation },
{ glGetSubroutineIndex_ENUM,                           "glGetSubroutineIndex",                           eglc_getSubroutineIndex },
{ glGetActiveSubroutineUniformiv_ENUM,                 "glGetActiveSubroutineUniformiv",                 eglc_getActiveSubroutineUniformiv },
{ glGetActiveSubroutineUniformName_ENUM,               "glGetActiveSubroutineUniformName",               eglc_getActiveSubroutineUniformName },
{ glGetActiveSubroutineName_ENUM,                      "glGetActiveSubroutineName",                      eglc_getActiveSubroutineName },
{ glUniformSubroutinesuiv_ENUM,                        "glUniformSubroutinesuiv",                        eglc_uniformSubroutinesuiv },
{ glGetUniformSubroutineuiv_ENUM,                      "glGetUniformSubroutineuiv",                      eglc_getUniformSubroutineuiv },
{ glGetProgramStageiv_ENUM,                            "glGetProgramStageiv",                            eglc_getProgramStageiv },
/* GL_ARB_tessellation_shader */
{ glPatchParameteri_ENUM,                              "glPatchParameteri",                              eglc_patchParameteri },
{ glPatchParameterfv_ENUM,                             "glPatchParameterfv",                             eglc_patchParameterfv },
/* GL_ARB_texture_buffer_object_rgb32 */
/* GL_ARB_transform_feedback2 */
{ glBindTransformFeedback_ENUM,                        "glBindTransformFeedback",                        eglc_bindTransformFeedback },
{ glDeleteTransformFeedbacks_ENUM,                     "glDeleteTransformFeedbacks",                     eglc_deleteTransformFeedbacks },
{ glGenTransformFeedbacks_ENUM,                        "glGenTransformFeedbacks",                        eglc_genTransformFeedbacks },
{ glIsTransformFeedback_ENUM,                          "glIsTransformFeedback",                          eglc_isTransformFeedback },
{ glPauseTransformFeedback_ENUM,                       "glPauseTransformFeedback",                       eglc_pauseTransformFeedback },
{ glResumeTransformFeedback_ENUM,                      "glResumeTransformFeedback",                      eglc_resumeTransformFeedback },
{ glDrawTransformFeedback_ENUM,                        "glDrawTransformFeedback",                        eglc_drawTransformFeedback },
/* GL_ARB_transform_feedback3 */
{ glDrawTransformFeedbackStream_ENUM,                  "glDrawTransformFeedbackStream",                  eglc_drawTransformFeedbackStream },
{ glBeginQueryIndexed_ENUM,                            "glBeginQueryIndexed",                            eglc_beginQueryIndexed },
{ glEndQueryIndexed_ENUM,                              "glEndQueryIndexed",                              eglc_endQueryIndexed },
{ glGetQueryIndexediv_ENUM,                            "glGetQueryIndexediv",                            eglc_getQueryIndexediv },
/* GL_ARB_ES2_compatibility */
{ glReleaseShaderCompiler_ENUM,                        "glReleaseShaderCompiler",                        eglc_releaseShaderCompiler },
{ glShaderBinary_ENUM,                                 "glShaderBinary",                                 eglc_shaderBinary },
{ glGetShaderPrecisionFormat_ENUM,                     "glGetShaderPrecisionFormat",                     eglc_getShaderPrecisionFormat },
{ glDepthRangef_ENUM,                                  "glDepthRangef",                                  eglc_depthRangef },
{ glClearDepthf_ENUM,                                  "glClearDepthf",                                  eglc_clearDepthf },
/* GL_ARB_get_program_binary */
{ glGetProgramBinary_ENUM,                             "glGetProgramBinary",                             eglc_getProgramBinary },
{ glProgramBinary_ENUM,                                "glProgramBinary",                                eglc_programBinary },
{ glProgramParameteri_ENUM,                            "glProgramParameteri",                            eglc_programParameteri },
/* GL_ARB_separate_shader_objects */
{ glUseProgramStages_ENUM,                             "glUseProgramStages",                             eglc_useProgramStages },
{ glActiveShaderProgram_ENUM,                          "glActiveShaderProgram",                          eglc_activeShaderProgram },
{ glCreateShaderProgramv_ENUM,                         "glCreateShaderProgramv",                         eglc_createShaderProgramv },
{ glBindProgramPipeline_ENUM,                          "glBindProgramPipeline",                          eglc_bindProgramPipeline },
{ glDeleteProgramPipelines_ENUM,                       "glDeleteProgramPipelines",                       eglc_deleteProgramPipelines },
{ glGenProgramPipelines_ENUM,                          "glGenProgramPipelines",                          eglc_genProgramPipelines },
{ glIsProgramPipeline_ENUM,                            "glIsProgramPipeline",                            eglc_isProgramPipeline },
{ glGetProgramPipelineiv_ENUM,                         "glGetProgramPipelineiv",                         eglc_getProgramPipelineiv },
{ glProgramUniform1i_ENUM,                             "glProgramUniform1i",                             eglc_programUniform1i },
{ glProgramUniform1iv_ENUM,                            "glProgramUniform1iv",                            eglc_programUniform1iv },
{ glProgramUniform1f_ENUM,                             "glProgramUniform1f",                             eglc_programUniform1f },
{ glProgramUniform1fv_ENUM,                            "glProgramUniform1fv",                            eglc_programUniform1fv },
{ glProgramUniform1d_ENUM,                             "glProgramUniform1d",                             eglc_programUniform1d },
{ glProgramUniform1dv_ENUM,                            "glProgramUniform1dv",                            eglc_programUniform1dv },
{ glProgramUniform1ui_ENUM,                            "glProgramUniform1ui",                            eglc_programUniform1ui },
{ glProgramUniform1uiv_ENUM,                           "glProgramUniform1uiv",                           eglc_programUniform1uiv },
{ glProgramUniform2i_ENUM,                             "glProgramUniform2i",                             eglc_programUniform2i },
{ glProgramUniform2iv_ENUM,                            "glProgramUniform2iv",                            eglc_programUniform2iv },
{ glProgramUniform2f_ENUM,                             "glProgramUniform2f",                             eglc_programUniform2f },
{ glProgramUniform2fv_ENUM,                            "glProgramUniform2fv",                            eglc_programUniform2fv },
{ glProgramUniform2d_ENUM,                             "glProgramUniform2d",                             eglc_programUniform2d },
{ glProgramUniform2dv_ENUM,                            "glProgramUniform2dv",                            eglc_programUniform2dv },
{ glProgramUniform2ui_ENUM,                            "glProgramUniform2ui",                            eglc_programUniform2ui },
{ glProgramUniform2uiv_ENUM,                           "glProgramUniform2uiv",                           eglc_programUniform2uiv },
{ glProgramUniform3i_ENUM,                             "glProgramUniform3i",                             eglc_programUniform3i },
{ glProgramUniform3iv_ENUM,                            "glProgramUniform3iv",                            eglc_programUniform3iv },
{ glProgramUniform3f_ENUM,                             "glProgramUniform3f",                             eglc_programUniform3f },
{ glProgramUniform3fv_ENUM,                            "glProgramUniform3fv",                            eglc_programUniform3fv },
{ glProgramUniform3d_ENUM,                             "glProgramUniform3d",                             eglc_programUniform3d },
{ glProgramUniform3dv_ENUM,                            "glProgramUniform3dv",                            eglc_programUniform3dv },
{ glProgramUniform3ui_ENUM,                            "glProgramUniform3ui",                            eglc_programUniform3ui },
{ glProgramUniform3uiv_ENUM,                           "glProgramUniform3uiv",                           eglc_programUniform3uiv },
{ glProgramUniform4i_ENUM,                             "glProgramUniform4i",                             eglc_programUniform4i },
{ glProgramUniform4iv_ENUM,                            "glProgramUniform4iv",                            eglc_programUniform4iv },
{ glProgramUniform4f_ENUM,                             "glProgramUniform4f",                             eglc_programUniform4f },
{ glProgramUniform4fv_ENUM,                            "glProgramUniform4fv",                            eglc_programUniform4fv },
{ glProgramUniform4d_ENUM,                             "glProgramUniform4d",                             eglc_programUniform4d },
{ glProgramUniform4dv_ENUM,                            "glProgramUniform4dv",                            eglc_programUniform4dv },
{ glProgramUniform4ui_ENUM,                            "glProgramUniform4ui",                            eglc_programUniform4ui },
{ glProgramUniform4uiv_ENUM,                           "glProgramUniform4uiv",                           eglc_programUniform4uiv },
{ glProgramUniformMatrix2fv_ENUM,                      "glProgramUniformMatrix2fv",                      eglc_programUniformMatrix2fv },
{ glProgramUniformMatrix3fv_ENUM,                      "glProgramUniformMatrix3fv",                      eglc_programUniformMatrix3fv },
{ glProgramUniformMatrix4fv_ENUM,                      "glProgramUniformMatrix4fv",                      eglc_programUniformMatrix4fv },
{ glProgramUniformMatrix2dv_ENUM,                      "glProgramUniformMatrix2dv",                      eglc_programUniformMatrix2dv },
{ glProgramUniformMatrix3dv_ENUM,                      "glProgramUniformMatrix3dv",                      eglc_programUniformMatrix3dv },
{ glProgramUniformMatrix4dv_ENUM,                      "glProgramUniformMatrix4dv",                      eglc_programUniformMatrix4dv },
{ glProgramUniformMatrix2x3fv_ENUM,                    "glProgramUniformMatrix2x3fv",                    eglc_programUniformMatrix2x3fv },
{ glProgramUniformMatrix3x2fv_ENUM,                    "glProgramUniformMatrix3x2fv",                    eglc_programUniformMatrix3x2fv },
{ glProgramUniformMatrix2x4fv_ENUM,                    "glProgramUniformMatrix2x4fv",                    eglc_programUniformMatrix2x4fv },
{ glProgramUniformMatrix4x2fv_ENUM,                    "glProgramUniformMatrix4x2fv",                    eglc_programUniformMatrix4x2fv },
{ glProgramUniformMatrix3x4fv_ENUM,                    "glProgramUniformMatrix3x4fv",                    eglc_programUniformMatrix3x4fv },
{ glProgramUniformMatrix4x3fv_ENUM,                    "glProgramUniformMatrix4x3fv",                    eglc_programUniformMatrix4x3fv },
{ glProgramUniformMatrix2x3dv_ENUM,                    "glProgramUniformMatrix2x3dv",                    eglc_programUniformMatrix2x3dv },
{ glProgramUniformMatrix3x2dv_ENUM,                    "glProgramUniformMatrix3x2dv",                    eglc_programUniformMatrix3x2dv },
{ glProgramUniformMatrix2x4dv_ENUM,                    "glProgramUniformMatrix2x4dv",                    eglc_programUniformMatrix2x4dv },
{ glProgramUniformMatrix4x2dv_ENUM,                    "glProgramUniformMatrix4x2dv",                    eglc_programUniformMatrix4x2dv },
{ glProgramUniformMatrix3x4dv_ENUM,                    "glProgramUniformMatrix3x4dv",                    eglc_programUniformMatrix3x4dv },
{ glProgramUniformMatrix4x3dv_ENUM,                    "glProgramUniformMatrix4x3dv",                    eglc_programUniformMatrix4x3dv },
{ glValidateProgramPipeline_ENUM,                      "glValidateProgramPipeline",                      eglc_validateProgramPipeline },
{ glGetProgramPipelineInfoLog_ENUM,                    "glGetProgramPipelineInfoLog",                    eglc_getProgramPipelineInfoLog },
/* GL_ARB_vertex_attrib_64bit */
{ glVertexAttribL1d_ENUM,                              "glVertexAttribL1d",                              eglc_vertexAttribL1d },
{ glVertexAttribL2d_ENUM,                              "glVertexAttribL2d",                              eglc_vertexAttribL2d },
{ glVertexAttribL3d_ENUM,                              "glVertexAttribL3d",                              eglc_vertexAttribL3d },
{ glVertexAttribL4d_ENUM,                              "glVertexAttribL4d",                              eglc_vertexAttribL4d },
{ glVertexAttribL1dv_ENUM,                             "glVertexAttribL1dv",                             eglc_vertexAttribL1dv },
{ glVertexAttribL2dv_ENUM,                             "glVertexAttribL2dv",                             eglc_vertexAttribL2dv },
{ glVertexAttribL3dv_ENUM,                             "glVertexAttribL3dv",                             eglc_vertexAttribL3dv },
{ glVertexAttribL4dv_ENUM,                             "glVertexAttribL4dv",                             eglc_vertexAttribL4dv },
{ glVertexAttribLPointer_ENUM,                         "glVertexAttribLPointer",                         eglc_vertexAttribLPointer },
{ glGetVertexAttribLdv_ENUM,                           "glGetVertexAttribLdv",                           eglc_getVertexAttribLdv },
/* GL_ARB_viewport_array */
{ glViewportArrayv_ENUM,                               "glViewportArrayv",                               eglc_viewportArrayv },
{ glViewportIndexedf_ENUM,                             "glViewportIndexedf",                             eglc_viewportIndexedf },
{ glViewportIndexedfv_ENUM,                            "glViewportIndexedfv",                            eglc_viewportIndexedfv },
{ glScissorArrayv_ENUM,                                "glScissorArrayv",                                eglc_scissorArrayv },
{ glScissorIndexed_ENUM,                               "glScissorIndexed",                               eglc_scissorIndexed },
{ glScissorIndexedv_ENUM,                              "glScissorIndexedv",                              eglc_scissorIndexedv },
{ glDepthRangeArrayv_ENUM,                             "glDepthRangeArrayv",                             eglc_depthRangeArrayv },
{ glDepthRangeIndexed_ENUM,                            "glDepthRangeIndexed",                            eglc_depthRangeIndexed },
{ glGetFloati_v_ENUM,                                  "glGetFloati_v",                                  eglc_getFloati_v },
{ glGetDoublei_v_ENUM,                                 "glGetDoublei_v",                                 eglc_getDoublei_v },
/* GL_ARB_cl_event */
{ glCreateSyncFromCLeventARB_ENUM,                     "glCreateSyncFromCLeventARB",                     eglc_createSyncFromCLeventARB },
/* GL_ARB_debug_output */
{ glDebugMessageControlARB_ENUM,                       "glDebugMessageControlARB",                       eglc_debugMessageControlARB },
{ glDebugMessageInsertARB_ENUM,                        "glDebugMessageInsertARB",                        eglc_debugMessageInsertARB },
{ glDebugMessageCallbackARB_ENUM,                      "glDebugMessageCallbackARB",                      eglc_debugMessageCallbackARB },
{ glGetDebugMessageLogARB_ENUM,                        "glGetDebugMessageLogARB",                        eglc_getDebugMessageLogARB },
/* GL_ARB_robustness */
{ glGetGraphicsResetStatusARB_ENUM,                    "glGetGraphicsResetStatusARB",                    eglc_getGraphicsResetStatusARB },
{ glGetnTexImageARB_ENUM,                              "glGetnTexImageARB",                              eglc_getnTexImageARB },
{ glReadnPixelsARB_ENUM,                               "glReadnPixelsARB",                               eglc_readnPixelsARB },
{ glGetnCompressedTexImageARB_ENUM,                    "glGetnCompressedTexImageARB",                    eglc_getnCompressedTexImageARB },
{ glGetnUniformfvARB_ENUM,                             "glGetnUniformfvARB",                             eglc_getnUniformfvARB },
{ glGetnUniformivARB_ENUM,                             "glGetnUniformivARB",                             eglc_getnUniformivARB },
{ glGetnUniformuivARB_ENUM,                            "glGetnUniformuivARB",                            eglc_getnUniformuivARB },
{ glGetnUniformdvARB_ENUM,                             "glGetnUniformdvARB",                             eglc_getnUniformdvARB },
/* GL_ARB_shader_stencil_export */
/* GL_ARB_base_instance */
{ glDrawArraysInstancedBaseInstance_ENUM,              "glDrawArraysInstancedBaseInstance",              eglc_drawArraysInstancedBaseInstance },
{ glDrawElementsInstancedBaseInstance_ENUM,            "glDrawElementsInstancedBaseInstance",            eglc_drawElementsInstancedBaseInstance },
{ glDrawElementsInstancedBaseVertexBaseInstance_ENUM,  "glDrawElementsInstancedBaseVertexBaseInstance",  eglc_drawElementsInstancedBaseVertexBaseInstance },
/* GL_ARB_shading_language_420pack */
/* GL_ARB_transform_feedback_instanced */
{ glDrawTransformFeedbackInstanced_ENUM,               "glDrawTransformFeedbackInstanced",               eglc_drawTransformFeedbackInstanced },
{ glDrawTransformFeedbackStreamInstanced_ENUM,         "glDrawTransformFeedbackStreamInstanced",         eglc_drawTransformFeedbackStreamInstanced },
/* GL_ARB_compressed_texture_pixel_storage */
/* GL_ARB_conservative_depth */
/* GL_ARB_internalformat_query */
{ glGetInternalformativ_ENUM,                          "glGetInternalformativ",                          eglc_getInternalformativ },
/* GL_ARB_map_buffer_alignment */
/* GL_ARB_shader_atomic_counters */
{ glGetActiveAtomicCounterBufferiv_ENUM,               "glGetActiveAtomicCounterBufferiv",               eglc_getActiveAtomicCounterBufferiv },
/* GL_ARB_shader_image_load_store */
{ glBindImageTexture_ENUM,                             "glBindImageTexture",                             eglc_bindImageTexture },
{ glMemoryBarrier_ENUM,                                "glMemoryBarrier",                                eglc_memoryBarrier },
/* GL_ARB_shading_language_packing */
/* GL_ARB_texture_storage */
{ glTexStorage1D_ENUM,                                 "glTexStorage1D",                                 eglc_texStorage1D },
{ glTexStorage2D_ENUM,                                 "glTexStorage2D",                                 eglc_texStorage2D },
{ glTexStorage3D_ENUM,                                 "glTexStorage3D",                                 eglc_texStorage3D },
{ glTextureStorage1DEXT_ENUM,                          "glTextureStorage1DEXT",                          eglc_textureStorage1DEXT },
{ glTextureStorage2DEXT_ENUM,                          "glTextureStorage2DEXT",                          eglc_textureStorage2DEXT },
{ glTextureStorage3DEXT_ENUM,                          "glTextureStorage3DEXT",                          eglc_textureStorage3DEXT },
/* GL_KHR_texture_compression_astc_ldr */
/* GL_KHR_debug */
{ glDebugMessageControl_ENUM,                          "glDebugMessageControl",                          eglc_debugMessageControl },
{ glDebugMessageInsert_ENUM,                           "glDebugMessageInsert",                           eglc_debugMessageInsert },
{ glDebugMessageCallback_ENUM,                         "glDebugMessageCallback",                         eglc_debugMessageCallback },
{ glGetDebugMessageLog_ENUM,                           "glGetDebugMessageLog",                           eglc_getDebugMessageLog },
{ glPushDebugGroup_ENUM,                               "glPushDebugGroup",                               eglc_pushDebugGroup },
{ glPopDebugGroup_ENUM,                                "glPopDebugGroup",                                eglc_popDebugGroup },
{ glObjectLabel_ENUM,                                  "glObjectLabel",                                  eglc_objectLabel },
{ glGetObjectLabel_ENUM,                               "glGetObjectLabel",                               eglc_getObjectLabel },
{ glObjectPtrLabel_ENUM,                               "glObjectPtrLabel",                               eglc_objectPtrLabel },
{ glGetObjectPtrLabel_ENUM,                            "glGetObjectPtrLabel",                            eglc_getObjectPtrLabel },
/* GL_ARB_arrays_of_arrays */
/* GL_ARB_clear_buffer_object */
{ glClearBufferData_ENUM,                              "glClearBufferData",                              eglc_clearBufferData },
{ glClearBufferSubData_ENUM,                           "glClearBufferSubData",                           eglc_clearBufferSubData },
{ glClearNamedBufferDataEXT_ENUM,                      "glClearNamedBufferDataEXT",                      eglc_clearNamedBufferDataEXT },
{ glClearNamedBufferSubDataEXT_ENUM,                   "glClearNamedBufferSubDataEXT",                   eglc_clearNamedBufferSubDataEXT },
/* GL_ARB_compute_shader */
{ glDispatchCompute_ENUM,                              "glDispatchCompute",                              eglc_dispatchCompute },
{ glDispatchComputeIndirect_ENUM,                      "glDispatchComputeIndirect",                      eglc_dispatchComputeIndirect },
/* GL_ARB_copy_image */
{ glCopyImageSubData_ENUM,                             "glCopyImageSubData",                             eglc_copyImageSubData },
/* GL_ARB_texture_view */
{ glTextureView_ENUM,                                  "glTextureView",                                  eglc_textureView },
/* GL_ARB_vertex_attrib_binding */
{ glBindVertexBuffer_ENUM,                             "glBindVertexBuffer",                             eglc_bindVertexBuffer },
{ glVertexAttribFormat_ENUM,                           "glVertexAttribFormat",                           eglc_vertexAttribFormat },
{ glVertexAttribIFormat_ENUM,                          "glVertexAttribIFormat",                          eglc_vertexAttribIFormat },
{ glVertexAttribLFormat_ENUM,                          "glVertexAttribLFormat",                          eglc_vertexAttribLFormat },
{ glVertexAttribBinding_ENUM,                          "glVertexAttribBinding",                          eglc_vertexAttribBinding },
{ glVertexBindingDivisor_ENUM,                         "glVertexBindingDivisor",                         eglc_vertexBindingDivisor },
{ glVertexArrayBindVertexBufferEXT_ENUM,               "glVertexArrayBindVertexBufferEXT",               eglc_vertexArrayBindVertexBufferEXT },
{ glVertexArrayVertexAttribFormatEXT_ENUM,             "glVertexArrayVertexAttribFormatEXT",             eglc_vertexArrayVertexAttribFormatEXT },
{ glVertexArrayVertexAttribIFormatEXT_ENUM,            "glVertexArrayVertexAttribIFormatEXT",            eglc_vertexArrayVertexAttribIFormatEXT },
{ glVertexArrayVertexAttribLFormatEXT_ENUM,            "glVertexArrayVertexAttribLFormatEXT",            eglc_vertexArrayVertexAttribLFormatEXT },
{ glVertexArrayVertexAttribBindingEXT_ENUM,            "glVertexArrayVertexAttribBindingEXT",            eglc_vertexArrayVertexAttribBindingEXT },
{ glVertexArrayVertexBindingDivisorEXT_ENUM,           "glVertexArrayVertexBindingDivisorEXT",           eglc_vertexArrayVertexBindingDivisorEXT },
/* GL_ARB_robustness_isolation */
/* GL_ARB_ES3_compatibility */
/* GL_ARB_explicit_uniform_location */
/* GL_ARB_fragment_layer_viewport */
/* GL_ARB_framebuffer_no_attachments */
{ glFramebufferParameteri_ENUM,                        "glFramebufferParameteri",                        eglc_framebufferParameteri },
{ glGetFramebufferParameteriv_ENUM,                    "glGetFramebufferParameteriv",                    eglc_getFramebufferParameteriv },
{ glNamedFramebufferParameteriEXT_ENUM,                "glNamedFramebufferParameteriEXT",                eglc_namedFramebufferParameteriEXT },
{ glGetNamedFramebufferParameterivEXT_ENUM,            "glGetNamedFramebufferParameterivEXT",            eglc_getNamedFramebufferParameterivEXT },
/* GL_ARB_internalformat_query2 */
{ glGetInternalformati64v_ENUM,                        "glGetInternalformati64v",                        eglc_getInternalformati64v },
/* GL_ARB_invalidate_subdata */
{ glInvalidateTexSubImage_ENUM,                        "glInvalidateTexSubImage",                        eglc_invalidateTexSubImage },
{ glInvalidateTexImage_ENUM,                           "glInvalidateTexImage",                           eglc_invalidateTexImage },
{ glInvalidateBufferSubData_ENUM,                      "glInvalidateBufferSubData",                      eglc_invalidateBufferSubData },
{ glInvalidateBufferData_ENUM,                         "glInvalidateBufferData",                         eglc_invalidateBufferData },
{ glInvalidateFramebuffer_ENUM,                        "glInvalidateFramebuffer",                        eglc_invalidateFramebuffer },
{ glInvalidateSubFramebuffer_ENUM,                     "glInvalidateSubFramebuffer",                     eglc_invalidateSubFramebuffer },
/* GL_ARB_multi_draw_indirect */
{ glMultiDrawArraysIndirect_ENUM,                      "glMultiDrawArraysIndirect",                      eglc_multiDrawArraysIndirect },
{ glMultiDrawElementsIndirect_ENUM,                    "glMultiDrawElementsIndirect",                    eglc_multiDrawElementsIndirect },
/* GL_ARB_program_interface_query */
{ glGetProgramInterfaceiv_ENUM,                        "glGetProgramInterfaceiv",                        eglc_getProgramInterfaceiv },
{ glGetProgramResourceIndex_ENUM,                      "glGetProgramResourceIndex",                      eglc_getProgramResourceIndex },
{ glGetProgramResourceName_ENUM,                       "glGetProgramResourceName",                       eglc_getProgramResourceName },
{ glGetProgramResourceiv_ENUM,                         "glGetProgramResourceiv",                         eglc_getProgramResourceiv },
{ glGetProgramResourceLocation_ENUM,                   "glGetProgramResourceLocation",                   eglc_getProgramResourceLocation },
{ glGetProgramResourceLocationIndex_ENUM,              "glGetProgramResourceLocationIndex",              eglc_getProgramResourceLocationIndex },
/* GL_ARB_robust_buffer_access_behavior */
/* GL_ARB_shader_image_size */
/* GL_ARB_shader_storage_buffer_object */
{ glShaderStorageBlockBinding_ENUM,                    "glShaderStorageBlockBinding",                    eglc_shaderStorageBlockBinding },
/* GL_ARB_stencil_texturing */
/* GL_ARB_texture_buffer_range */
{ glTexBufferRange_ENUM,                               "glTexBufferRange",                               eglc_texBufferRange },
{ glTextureBufferRangeEXT_ENUM,                        "glTextureBufferRangeEXT",                        eglc_textureBufferRangeEXT },
/* GL_ARB_texture_query_levels */
/* GL_ARB_texture_storage_multisample */
{ glTexStorage2DMultisample_ENUM,                      "glTexStorage2DMultisample",                      eglc_texStorage2DMultisample },
{ glTexStorage3DMultisample_ENUM,                      "glTexStorage3DMultisample",                      eglc_texStorage3DMultisample },
{ glTextureStorage2DMultisampleEXT_ENUM,               "glTextureStorage2DMultisampleEXT",               eglc_textureStorage2DMultisampleEXT },
{ glTextureStorage3DMultisampleEXT_ENUM,               "glTextureStorage3DMultisampleEXT",               eglc_textureStorage3DMultisampleEXT },

#endif // COMPILE_GLCOREARB
